### ISSUE TITLE
Add API to show/hide series without removing it

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#471] opened 2020-06-09 07:00 UTC
I mean to show a line series legend somewhere at the left top corner of a plot and to have an abillity to turning visibility on and off to some of them. What about such feature?

**Comment by timocov** [comment] 2020-06-10 07:40
I'd say it's duplicate of https://github.com/tradingview/lightweight-charts/issues/42#issuecomment-502017406, but we need to investigate it one more time.

**Closed** 2020-09-22 11:37 UTC
Labels: enhancement
