### ISSUE TITLE
Support new price scale position for price scale is behind of chart

### ISSUE THREAD

**Issue by sanghavan** [tradingview/lightweight-charts#473] opened 2020-06-09 18:49 UTC
For right now, priceScale position there are 3 options:

- left
- right 
- none

When using `position: none`, the chart is full width, but priceScale is gone. I would like to request a new position for full width chart and it's in front of priceScale. Like the Binance app screenshot

![image](https://user-images.githubusercontent.com/6092132/84187141-cd686a80-aabb-11ea-95d4-312088d922a3.png)
Thank you!

**Comment by timocov** [comment] 2020-06-10 07:44
Duplicate of #208

**Closed by timocov** 2020-06-10 07:44 UTC
