### ISSUE TITLE
How to add multiple charts in a tab

### ISSUE THREAD

**Issue by gebilaofan** [tradingview/lightweight-charts#223] opened 2019-09-30 06:40 UTC
I now have a web page that can be dynamically added. When I select the time, line type, and product, click the button to add a tab to generate a new chart. I have a problem now, the newly added chart will take the data of the previous chart, like this.

![image](https://user-images.githubusercontent.com/46524158/65854630-bb142980-e38f-11e9-86cc-d4b2c9dfa261.png)

![image](https://user-images.githubusercontent.com/46524158/65854690-d7b06180-e38f-11e9-90f5-389a6cc09ba8.png)

```js
<div class="addTrace" @click="addTab(editableTabsValue)">
	<img src="../assets/trace/shouye_icon_tj.png" alt="">
</div>

<el-tabs v-model="editableTabsValue" id="tab-box" type="card" :closable='isClosable' @tab-remove='removeTab'> 
				<el-tab-pane
				v-for="(item) in editableTabs"
				:key="item.name"
				:label="item.title"
				:name="item.name"
				>
					<div  v-for="(item, index) in editableTabs" :key="index" style="height:100%">
						<TraceComponent @updataUserMoney='getUserMoney'> // chart component
						</TraceComponent>
					</div>
				</el-tab-pane>
			</el-tabs>
```

Am I adding an identifier to the chart to distinguish them?

**Comment by eugene-korobko** [comment] 2019-09-30 14:15
Hello!

I could suppose that the problem is relared to z-order.
Do you try to place one chart over another?

**Comment by gebilaofan** [comment] 2019-10-08 02:23
> Hello!
> 
> I could suppose that the problem is relared to z-order.
> Do you try to place one chart over another?

No, this is a tab switch, there is a dynamic add delete feature. Just like this example https://element.eleme.cn/#/zh-CN/component/tabs#zi-ding-yi-zeng-jia-biao-qian-ye-hong-fa-qi
The chart component is added, and the display is hidden by display:none

**Comment by timocov** [comment] 2019-10-16 07:40
> Am I adding an identifier to the chart to distinguish them?

For the library itself it's not required, so it could be just any div without any id-like kind (you need to pass different containers only).

@gebilaofan can you please provide link or jsfiddle-like (sandbox maybe) example where we can see that problem?

**Comment by gebilaofan** [comment] 2019-10-23 09:19
The problem arises when I add a new chart, the two charts share the same chartId. So there will be more than one data on a chart, so if I add a chart, create a different chartId. When I add the modified data to the two charts, they won't affect it.

**Comment by timocov** [comment] 2019-10-23 15:07
@gebilaofan Sorry, I'm not sure that understand you correctly. Can you please provide link to your page or even better jsfiddle-like example?

**Comment by nikitamarcius** [comment] 2019-10-24 05:50
@gebilaofan need different containers with different identifiers like `id="cont1",  id="cont2"` as I wrote above @timocov 

if using js framework like vuejs https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

Refs allows you to manage DOM el inside a component

**Comment by gebilaofan** [comment] 2019-10-24 07:31
@nikitamarcius Yes, it is like this

**Comment by nikitamarcius** [comment] 2019-10-24 14:11
@gebilaofan I do otherwise. I have routing (url path), when it changes "localhost/market/<btcusdt>", the component is re-rendered. If I need to add another graph "+", I open a modal window

**Comment by timocov** [comment] 2019-11-20 09:09
@nikitamarcius @gebilaofan is the problem still here? Looks like this thread is silent for some time and I'm not sure is the issue fixed or not.

**Comment by nikitamarcius** [comment] 2019-11-20 18:25
@timocov im ok. I think u can close it, @gebilaofan  will be able to reopen if necessary

**Comment by timocov** [comment] 2019-11-21 09:08
Ok, @gebilaofan if you'll have any question or updates - feel free to re-open it.

**Closed by timocov** 2019-11-21 09:08 UTC
Labels: question
