### ISSUE TITLE
Candlestick 1min interval?

### ISSUE THREAD

**Issue by petekblaz** [tradingview/lightweight-charts#667] opened 2020-12-31 15:31 UTC
In candlestick chart, each wick is 1 day.. how do i instead show 1 minute wicks?

**Comment by neeschit** [comment] 2021-01-01 16:54
```
var chart = LightweightCharts.createChart(document.body, {
	timeScale: {
		timeVisible: true,
                secondsVisible: false,
	},
});
```

**Comment by timocov** [comment] 2021-01-11 08:07
Duplicate of #674 642

**Closed by timocov** 2021-01-11 08:07 UTC
