### ISSUE TITLE
Error in importing library

### ISSUE THREAD

**Issue by nantha42** [tradingview/lightweight-charts#608] opened 2020-10-30 07:40 UTC
I have node js 15 version. But when I typed require('lightweight-charts') in interactive mode, I get the following error. 
```
require('lightweight-charts')
```
```
/Users/nantha/Projc/Js/node_modules/lightweight-charts/dist/lightweight-charts.esm.development.js:7
import { bindToDevicePixelRatio } from 'fancy-canvas/coordinate-space';
^^^^^^

Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import
```
What I have done wrong?

**Comment by timocov** [comment] 2020-10-30 18:01
> What I have done wrong?

You import client-side library in NodeJS context :)

**Comment by timocov** [comment] 2020-10-30 18:02
Duplicate of https://github.com/tradingview/lightweight-charts/issues/543

**Closed by timocov** 2020-10-30 18:02 UTC
