### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by darwin403** [tradingview/lightweight-charts#936] opened 2021-12-13 13:50 UTC
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:**

The package in this example lightweight-charts is not working with Next.js but works just fine on React.js. The same module and exactly the same code has been used for you to quickly compare that it works outside Next.js:

Next.js Example (NOT working): https://codesandbox.io/s/eloquent-snowflake-ucill?file=/pages/index.js
React.js Example (working): https://codesandbox.io/s/flamboyant-danny-jbtsk?file=/src/App.js

**Actual behavior:**

Fails to import module with an error

**Expected behavior:**

Should import the module properly

**Screenshots:**
![https-ucill-sse-codesandbox-io](https://user-images.githubusercontent.com/65121170/145824123-f7eb6fc5-0fb8-4f4e-96db-e66ad74900f0.png)

**CodeSandbox/JSFiddle/etc link:**

https://codesandbox.io/s/eloquent-snowflake-ucill?file=/pages/index.js

**Comment by timocov** [comment] 2021-12-13 14:23
Duplicate of #543

**Closed by timocov** 2021-12-13 14:23 UTC
