### ISSUE TITLE
Show Candlestick data on hover

### ISSUE THREAD

**Issue by dominhtri1995** [tradingview/lightweight-charts#520] opened 2020-07-09 05:11 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to find the option to show Candlestick data (Open, High, Low, Close, Volume) when user hover on a candle. However it doesn't look like it's supported at the moment.

**Describe the solution you'd like**
Show Candlestick data on hover. It can be in a pop up or at the left corner like in the Tradingview JS library.

Am I missing something or it's indeed not supported ? Thank you.

Here is an example : https://www.highcharts.com/demo/stock/candlestick/sand-signika

**Comment by timocov** [comment] 2020-07-09 07:35
Duplicate of #153

**Comment by timocov** [comment] 2020-07-09 07:35
We won't do it inside the library (because the library is about charting itself), so you need to implement it outside of the library in your code.

**Closed by timocov** 2020-07-09 07:35 UTC
