### ISSUE TITLE
Add API to enter/exit in tracking mode

### ISSUE THREAD

**Issue by SimonVillage** [tradingview/lightweight-charts#376] opened 2020-03-10 09:30 UTC
We are using the library mostly for mobile. When focusing the chart on mobile, you will get the crosshair with price / time information. If you remove your finger, the crosshair does not reset / blur. Is there any way to call that event?

I am actually looking for the event which is called when clicking the chart one more time which makes then looses the focus on the chart and makes the crosshair disappear.

**Comment by timocov** [comment] 2020-03-10 09:57
> If you remove your finger, the crosshair does not reset / blur. Is there any way to call that event?

This is by design. It's called "tracking mode" and afaik it works on mobile only. To disable it an user needs to tap on the chart one more time. It allows you select a bar on touch devices properly and have it "selected" until an user wish it.

> I am actually looking for the event which is called when clicking the chart one more time which makes then looses the focus on the chart and makes the crosshair disappear.

So you want to have a way to force exit from tracking mode, right?

**Comment by SimonHausdorf** [comment] 2020-03-10 09:59
> So you want to have a way to force exit from tracking mode, right?

correct

**Comment by timocov** [comment] 2020-03-10 10:04
I marked it as feature request, but meantime can you please tell more about your case? Why do you want it? Maybe tracking mode doesn't work for you well? Previously we made it for www.tradingview.com/chart and I didn't hear any request to have "fast exit" from tracking mode. I assume that we might miss something...

**Comment by SimonHausdorf** [comment] 2020-03-10 10:09
we are using webview for the chart. We would like to get something similar as shown in the gif. Robinhood as example is using the same feature. The user can check the historical price and tracking will reset as soon as he lifts his finger avoiding an extra click to reset. In the meantime, is there any workaround which could work to stop tracking?

![ezgif-3-657251001f51](https://user-images.githubusercontent.com/1446685/76301869-ae451b80-62c7-11ea-9c08-782504a362fa.gif)

**Comment by timocov** [comment] 2020-03-10 16:53
I just asked the team why we've changed that behavior on www.tradingview.com: the reason is that users didn't like that when you move your finger and if tooltip is shown nearly the finger, so you can't really see what is on that tooptip. And I do understand them - I just that one of the app I'm using for trading and it has exactly the same problem, you need to move your finger a bit higher or lower to see what is there...

But anyway I agree that we can add API to force exit from tracking mode (or even option to override that behavior).

**Comment by SlicedSilver** [comment] 2022-08-26 15:30
Related: https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ChartOptions#trackingmode

**Comment by SlicedSilver** [comment] 2023-10-04 14:01
You could use an approach like this: https://tradingview.github.io/lightweight-charts/tutorials/how_to/set-crosshair-position#tracking-without-long-press-on-mobile

Essentially, you can disable the event listeners which LWC adds then handle the crosshair position yourself. This will achieve the similar effect.

**Closed by SlicedSilver** 2023-10-04 14:01 UTC
Labels: enhancement, need proposal, need more feedback
