### ISSUE TITLE
Installing lightweight-charts in react project breaks react

### ISSUE THREAD

**Issue by Cybermb** [tradingview/lightweight-charts#771] opened 2021-06-19 21:01 UTC
**Steps/code to reproduce:**

npx create-react-app my-app --template typescript
npm install lightweight-charts

**Result**
Unusable react app. While installing this library, it somehow breaks react packages

**Comment by timocov** [comment] 2021-06-21 13:47
Just wonder what can happen so one package might break another one.

> Unusable react app

What does it mean?

> it somehow breaks react packages

How did you notice it? What happened?

> Steps/code to reproduce

Is it all you did to reproduce it? What nodejs version you have? What npm version?

**Comment by Cybermb** [comment] 2021-06-21 21:10
By unusable react app I mean the app does not compile, JSX does not work, react import statements shows as not found by typescript.
 NPM version: 6.14.13
 Node version 14.17.1
And yes, thats two commands to reproduce the issue. While installing this library with npm, I have noticed that it takes longer than creating react boilerplate. Also observed that it removes lots of packages under installation, which might be the case.
To solve the issue i ran npm install again. However, I expect this library to not remove any existing packages.

**Comment by timocov** [comment] 2021-06-22 07:50
> While installing this library with npm, I have noticed that it takes longer than creating react boilerplate. Also observed that it removes lots of packages under installation, which might be the case.

Didn't you try to run `yard add lightweight-charts`? It seems that when you run `npx create-react-app my-app --template typescript` it uses `yarn` to install packages, that's why you see changes in node_modules. Also, you can run `npm install` right after `npx create-react-app my-app --template typescript` just to make sure that your node_modules are "created" with npm.

Thus, since it is not related to `lightweight-charts` I'm going to close this issue. I think that you might have the same issue with any other package you may use.

**Closed by timocov** 2021-06-22 07:50 UTC
