### ISSUE TITLE
BTCINCH1

### ISSUE THREAD

**Issue by promethus18** [tradingview/lightweight-charts#728] opened 2021-04-21 17:58 UTC
**Lightweight Charts Version:** 

**Steps/code to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment] 2021-04-22 08:51
Duplicate of #729

**Closed by timocov** 2021-04-22 08:51 UTC
