### ISSUE TITLE
Series-based markers

### ISSUE THREAD

**Issue by andresberrios** [tradingview/lightweight-charts#24] opened 2019-06-03 18:31 UTC
Hi! Thanks for the great work on this library.
I couldn't find in the docs any info on whether it's possible to plot a series of potentially sparse points that would be shown with some icon for each point on the chart, or maybe something like the possibility to add annotations.
The use case I'm after is being able to show on the chart specific points in time/price where something happened, such as real world events that might have affected the price, etc.
I'm not yet very familiar with the codebase of the library, but it seems to me that the simplest way to implement something like this would be to support a kind of "scatter series" that would allow you to specify an icon (image or char?) to plot each point with, which could coexist with a normal candlestick series for example, and could show a popover with details about that specific point (potentially arbitrary text) when hovered by the user.
Any way to do something like this now? If not, would it eventually be added?
Thanks again!

**Comment by timocov** [comment] 2019-06-04 16:55
Hi,

thank you for interest in this library, we're appreciate this.

> I couldn't find in the docs any info on whether it's possible to plot a series of potentially sparse points that would be shown with some icon for each point on the chart, or maybe something like the possibility to add annotations.

Yeah, currently we haven't API.

> it seems to me that the simplest way to implement something like this would be to support a kind of "scatter series" that would allow you to specify an icon (image or char?) to plot each point with

We've thought about it, and going to implement "events series" (or something like that) in the future, which will allow you draw events/marks above/below series (or even "on timescale").

But for now we're stabilizing the current API and the implementation to publish v1.

**Comment by andresberrios** [comment] 2019-06-05 19:08
Sounds great! Looking forward to it.
Would be great if it supported setting both the X and Y coordinates for each event (time and price), and if price is not specified, it could draw them above/below another series, or "on timescale" as you mentioned. Would be a great feature!

**Comment by Numbers88s** [comment] 2019-07-03 02:01
I want to add by saying thank you for the great library and +1 for this feature, especially for candlestick charts. I'd love to add annotations or a marker for specific events. Thanks again!

**Comment by srv91** [comment] 2019-07-11 07:53
+1 for this feature. Thanks!

**Comment by tghilardi** [comment] 2019-07-12 01:27
+1 for this feature. Thanks!

**Comment by timocov** [comment] 2019-07-12 10:39
Everyone who comment this as "+1" or something like that:

1. This feature already on 1.1 milestone and will be done soon.
1. Instead of commenting with "+1" you can just put your "+1" emoji on the first message 😉 
1. If you really need this feature, instead of "+1" comment it would be great if you provide your user-story (description, screenshots, etc) what exactly you need and how you'll use it - it helps us make it good for all of us and cover the most cases.

/cc @tghilardi @srv91 @Numbers88s

**Comment by srv91** [comment] 2019-07-12 11:39
@timocov Thanks for the direction :)

My use case is to build kind of a trading journal, where I can plot the trades/activities by a user as events with underlying candles(data) over a period of time.
I like the feature that the data can be streamed as well.
Sorry, I haven't checked this in the docs, but would be great if there's an option to:
1. have multiple line series and annotations on a chart and show the corresponding values on the tooltip.
2. hide/show these annotations.

Thanks!

**Comment by timocov** [comment] 2019-07-12 11:46
> have multiple line series and annotations on a chart and show the corresponding values on the tooltip.

Do you want to show the tooltip on hover or after click?

What do you want to show on these event markers? Letter? Just circle filled by color? Something else?

> hide/show these annotations.

All of them at once, or only specific events?

Also, where do you want to place them: below/under specific prices or bars? Right under the time axis?

**Comment by tghilardi** [comment] 2019-07-12 18:07
I want to be able to plot where I buy and sell to offer a visual way to find out whether entry and exits are optimal or need improvements. @timocov

**Comment by timocov** [comment] 2019-07-12 20:07
> I want to be able to plot where I buy and sell

@tghilardi What do you want to plot? Circles, arrows, or something else?

/cc @srv91

**Comment by tghilardi** [comment] 2019-07-12 20:14
Up and down arrows would be perfect, but anything would work.

**Comment by awunder** [comment] 2019-07-13 08:27
i'd love to be able to draw rectangles and lines on the chart.. doesnt need to be a UI for it, programmatically is fine..

i know its a little more than just an icon but to me this still counts as an annotation ;)

**Comment by srv91** [comment] 2019-07-13 08:49
@timocov

> Do you want to show the tooltip on hover or after click?

Tooltips by default would be better on hover. But I guess best would be to have a callback each for hover and click so this behaviour can be modified, if required.

> What do you want to show on these event markers? Letter? Just circle filled by color? Something else?

Circles filled by colours would do. But with this, there’ll be a need for legends which would solve the requirement of multiple types of events represented by different colours. Chartjs library has this feature of hiding/showing series onclick of respective legends. That’d be great :)

> Also, where do you want to place them: below/under specific prices or bars? Right under the time axis?

Best if it supports the x and y co-ordinates. So, each annotation/event object can have whatever meta to be shown on the tooltip and co-ordinates for positioning.

**Comment by timocov** [comment] 2019-07-13 19:04
> i'd love to be able to draw rectangles and lines on the chart.. doesnt need to be a UI for it, programmatically is fine..

@awunder I believe you need to create another issue for that because it's a little bit another case (it's about creating something like linetools: rectangles, trend lines and so on - we don't have a plan to them yet, but it might be discussing in the future).

> Best if it supports the x and y co-ordinates. So, each annotation/event object can have whatever meta to be shown on the tooltip and co-ordinates for positioning.

@srv91 if you'll provide coordinates as price/time then circle on price 100 (for instance) will overlap series' point with the same price. I don't think that it's what we want to have, right (series' point and event marker will be overlap each other)? I think we want to have that point right above/below series' point to show that here was something interesting? This might not be what do you expect for.

> Chartjs library has this feature of hiding/showing series onclick of respective legends. That’d be great :)

@srv91 could you please show an example/link to that feature?

> legends which would solve the requirement of multiple types of events represented by different colours

@srv91 did I understand you correct that in this case you'll add new "event series" for each "type of events" (new series for each type/color of event)?

> Up and down arrows would be perfect because that way I'd know if it was a short or a buy.

@tghilardi where do you want to draw them: right above/below series' price or on specific price?

**Comment by timocov** [comment] 2019-07-13 19:11
Just to summarize:

1. We want to draw some events/markers on the chart.
1. At the moment required types of the marker are: "filled by color circle", "up/down arrow".
1. There should be a callbacks for both hover and click events on a marker.

Questions:

1. Where markers should be drawn (or how to set coordinated for them): "below/above (series') price", "above time axis", "right at specific price", etc?

Am I missed something?

**Comment by jimeney** [comment] 2019-07-13 21:39
Feature wise, mimicking the capabilities of createShape and createMultipointShape in the full JS lib would be ideal. It would also make for a more frictionless migration for developers who may currently be using the full TradingView JS library but only require the means to create annotated/drawn charts systematically rather than offering up the full suite of capabilities

**Comment by jimeney** [comment] 2019-07-13 21:43
I'd be interested to know the long term ambition for this product/the boundaries you've been set, aside from keeping it 'lightweight', to understand how far the capabilities would likely be pushed towards functions currently in the full library

**Comment by timocov** [comment] 2019-07-13 22:08
> I'd be interested to know the long term ambition for this product/the boundaries you've been set, aside from keeping it 'lightweight', to understand how far the capabilities would likely be pushed towards functions currently in the full library

Great suggestion, thank you! I believe we should create a document/issue where we'll describe that so everyone can see them.

/cc @ezhukovskiy

**Comment by tghilardi** [comment] 2019-07-14 18:04
I want to be able to plot an arrow or an icon on the price that the security was bought or sold. Ideally multiple times on a chart. If this could be done via get, even better. For example ?chart=MSFT&buy=60.30,60,60,60,70&sell60.50,61.00,62,00&date=2019-02-02,2019-02-02&time=122303,122343,123243 and it would plot a total of 6 points, 3 buys and 3 sells at those exact timestamps. @timocov

**Comment by srv91** [comment] 2019-07-15 08:12
@timocov 
 > if you'll provide coordinates as price/time then circle on price 100 (for instance) will overlap series' point with the same price. I don't think that it's what we want to have, right (series' point and event marker will be overlap each other)? I think we want to have that point right above/below series' point to show that here was something interesting? This might not be what do you expect for.

Check this:
![image](https://user-images.githubusercontent.com/9715135/61202657-bd0e0b00-a705-11e9-949f-3f13c8497f02.png)

In the above screenshot, you'd see overlapping events on another series seems fine (but yeah, in this case the events are tightly coupled with the line series).
You'd also find another event legend (represented by orange circle), struck off which is the behavior for hiding/showing any series.

>  did I understand you correct that in this case you'll add new "event series" for each "type of events" (new series for each type/color of event)?

Yes, that's correct.

**Comment by timocov** [comment] 2019-07-16 17:11
Hi there,

after internal discussion about implementation for this feature we've decide the following (all names isn't final and might be changed while developing):

- We add new method to [ISeriesApi](https://github.com/tradingview/lightweight-charts/blob/v1.0.0/src/api/iseries-api.ts#L21-L58) (something like `setMarks`).
- In that method you should pass an array of series marks.
- Each series mark is an object with the following keys:
    - `time`
    - `position` - might be one of `aboveBar`, `belowBar` and `inBar`
    - `shape` - might be one of `circle`, `square`, `arrowUp`, `arrowDown`
    - `color` - color of the shape
    - `id` - id of the mark, will be passed to click/hover handlers (see below)

- All marks below or above bar is stacked (order defined by order in original array)
- Stacked marks extend autoscale price range, but not at all (for 2-3 marks max) - this is to avoid shrink series into the direct line
- Size (height and width) of the event is dependent of current bar spacing and cannot be changed (at least in the first version)
- Marks _don't_ extend time scale, if there is no series' data item for a mark then will be used neighbor point
- Click/crosshair moved event's info will be contains information about what series is clicked/hovered and what id of the mark is clicked/hovered

I hope I don't forget something 🙂 

What do you think guys about that? Is this enough for your cases or you want to change something?

I believe we'll start develop this feature on the next week so I think we've enough time to discuss it.

/cc @andresberrios @Numbers88s @srv91 @tghilardi @awunder @jimeney @ezhukovskiy @kirchet @eugene-korobko

**Comment by Numbers88s** [comment] 2019-07-16 17:13
Sounds great! Thank you!

**Comment by andresberrios** [comment] 2019-07-16 19:18
@timocov glad to see you are moving forward with this!
The implementation you are proposing would work well for some people/cases but not so well for others. Particularly, I'm interested in placing the mark at the exact price where the event (like buy or sell) happened, not just above of below the bar. This is because if a bar has a long range (open and close values being far apart, for example), then I want the marker to be placed at the point (or maybe right below the point, with the tip of the arrow placed exactly in the point) in which the buy happened.

So it sounds to me like this could be implemented as a kind of "scatter" series where each data point would be defined like this:

- `x`: Time in which the event happened.
- `y`: Price where the event happened.
- `anchor`: `[0..1, 0..1]`. Specifies where in the bounding box of the marker the `(x, y)` point should be. Examples: Giving `[0, 0]` would mean top-left, `[1, 0]` would mean bottom-left, `[0, 1]` would mean bottom-right, `[0, 0.5]` would mean top-center, and giving `[0.5, 0.5]` would mean center-center. This would allow users to draw it in any way they want. An upwards arrow icon could be used to represent a buy, the exact `(x, y) = (time, price)` could be used as position for the marker, and the anchor could be set at `[0.5, 0]` to make the tip of the arrow be aligned exactly with the (time, price) point.
- `marker`: Could be a character or a path to a small image file (or an actual [Image object](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image)), and additionally the library could provide some basic markers (dot, star, arrow, etc) and colors of those markers (could be specified like `['star', 'yellow']` or `['dot', '#34ff66']`).
- `rotation`: Just an idea, would maybe be useful to have a rotation parameter, that way you can have just one image for upward and downward arrow, and just rotate it to reuse it. Not essential though.
- `details`: A string to show additional information when the user hovers over the marker.

What do you think? Would this be possible? I think doing it this way would make it flexible enough to cover all the use cases that have been brought up.
Once again, thanks for the great work.

**Comment by jimeney** [comment] 2019-07-16 23:34
> * Marks _don't_ extend time scale, if there is no series' data item for a mark then will be used neighbor point

I appreciate the thought behind this is likely that of performance, but there would be some examples, for example the intersection of trendline forward projections, or in the event of plotting something like upcoming news / stock results type events for reference, might dictate plotting into the future.

**Comment by timocov** [comment] 2019-07-17 08:22
Suggestion from https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-511904914 is about marks on series only.

> Particularly, I'm interested in placing the mark at the exact price where the event (like buy or sell) happened, not just above of below the bar. 

@andresberrios Yes, we've discuss this case too and I believe we'll implement it in other way (similar to current, but that marks will not be "attached" to a series - it will be another "events/marks" series, which will be independent of any other series).
I'm not sure should we mix them in one issue/PR - it might block to release other features.

> Specifies where in the bounding box of the marker the (x, y) point should be. Examples: Giving [0, 0] would mean top-left, [1, 0] would mean bottom-left, [0, 1] would mean bottom-right, [0, 0.5] would mean top-center, and giving [0.5, 0.5] would mean center-center

@andresberrios "top-left"/"bottom-left"/"bottom-right"/"top-center"/"center-center" of what? We just provide a price and time where event is happened. In this case I can imagine only horizontal align because of bar spacing.

> details: A string to show additional information when the user hovers over the marker.

I don't think that we'll add it, because it requires showing tooltip (or something like that), but there is a lot websites and a lot custom design. What design we should use for them? I believe it can be done by users in the way they want and in the design they want.

> I appreciate the thought behind this is likely that of performance, but there would be some examples, for example the intersection of trendline forward projections, or in the event of plotting something like upcoming news / stock results type events for reference, might dictate plotting into the future.

@jimeney as I said, that suggestion is about markers attached for series. In this case there is cannot be "future" or "past" - there is no bars actually and we can't attach the marker to bar.

Let's leave this issue for series-based markers. We'll implement other type of markers, but it requires another discussion and providing you suggestion of implementation.

I just created #127 for markers series. If you have any suggestion for that series - please leave it there. As soon this topic is very popular of users, I believe we'll implement it soon, but after 1.1 with series-based markers.

**Comment by timocov** [comment] 2019-07-17 08:24
Quite possible that we'll need to add timescale-based markers to draw them right above timescale, but it looks like nobody asks it yet.

**Comment by fortsm** [comment] 2019-07-17 08:31
> Quite possible that we'll need to add timescale-based markers to draw them right above timescale, but it looks like nobody asks it yet.

I need this feauture.

**Comment by timocov** [comment] 2019-07-17 08:48
@fortsm great! Just look at #128 and leave your comment - what do you want, how do you see it, your usage and so on.

**Comment by bmatusiak** [comment] 2019-07-19 16:22
here is an image for what im looking for,

https://i.imgur.com/TRt6gjx.png

**Closed** 2019-08-26 09:35 UTC
Labels: enhancement

**Comment by hazhir1811** [comment] 2019-09-01 21:33
it seems like mark series are plotting one day behind of the provided day! check this out .

```
candleSeries.setMarkers([
	{
		time: '2019/09/01',
                position: 'aboveBar',
                color: 'yellow',
		shape: 'arrowDown',
	}
]);
```

the provided time => 2019/09/01 
but the ploted time is => 2019/08/31 

i know i am using another timezone but i checked this on UTC still the same, also checked this on 1D timeframe nothing changed , have done something wrong or is this a bug or something?

thanks for the great work. 

<img width="1440" alt="Screen Shot 2019-09-02 at 1 58 44 AM" src="https://user-images.githubusercontent.com/17275314/64082506-5aa8b280-cd25-11e9-8d99-c0cc6bcdc9e7.png">

**Comment by timocov** [comment] 2019-09-02 06:39
@hazhir1811 can you provide JSFiddle (or any other tools like this one) example?

> the provided time => 2019/09/01

Also, please pay attention that "2019/09/01" a little bit different than "2019-09-01".

![image](https://user-images.githubusercontent.com/3112183/64094762-6ddb7280-cd65-11e9-94b5-01f5f3b17152.png)

Did you try to change dates to format with dashes instead of slashes?

**Comment by hazhir1811** [comment] 2019-09-02 19:17
> @hazhir1811 can you provide JSFiddle (or any other tools like this one) example?
> 
> > the provided time => 2019/09/01
> 
> Also, please pay attention that "2019/09/01" a little bit different than "2019-09-01".
> 
> ![image](https://user-images.githubusercontent.com/3112183/64094762-6ddb7280-cd65-11e9-94b5-01f5f3b17152.png)
> 
> Did you try to change dates to format with dashes instead of slashes?

found the solution it if i create the timedate with "/" like this for example '2019/09/01' the plotted marker goes one day behind but if is use '2019-09-01' the problem is solved it will plot correctly.

**Comment by tghilardi** [comment] 2019-09-09 19:19
I know this was implemented, however, I cannot get it to work based on the documentation provided. Can anyone shed some light and provide a fiddle to look at?

**Comment by timocov** [comment] 2019-09-10 09:19
@tghilardi you can take a look at our e2e test cases https://github.com/tradingview/lightweight-charts/tree/master/tests/e2e/graphics/test-cases/series-markers

**Comment by tghilardi** [comment] 2019-09-10 13:27
Thanks @timocov I was running 1.0.0 and I got it to work.

**Comment by ackimwilliams** [comment] 2020-01-04 21:54
@timocov  ref: https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-511904914, https://github.com/tradingview/lightweight-charts/issues/24#issuecomment-513290612 

For intraday charts, I am looking to add random marks along a stock chart eg. https://i.imgur.com/TRt6gjx.png

When i add multiple marks to the chart they all stack. I saw that you hinted that this is by design but is there a way to place marks along the stock chart without having them all stack. It seems pretty useless to have all marks stack on the chart.

![image](https://user-images.githubusercontent.com/4093815/71772071-bc1aa100-2f12-11ea-9ae9-117bee6d366b.png)

**Comment by topaciotrade** [comment] 2021-11-26 04:06
> > @hazhir1811 can you provide JSFiddle (or any other tools like this one) example?
> > > the provided time => 2019/09/01
> > 
> > 
> > Also, please pay attention that "2019/09/01" a little bit different than "2019-09-01".
> > ![image](https://user-images.githubusercontent.com/3112183/64094762-6ddb7280-cd65-11e9-94b5-01f5f3b17152.png)
> > Did you try to change dates to format with dashes instead of slashes?
> 
> found the solution it if i create the timedate with "/" like this for example '2019/09/01' the plotted marker goes one day behind but if is use '2019-09-01' the problem is solved it will plot correctly.

Great But you also can create another serie and set the data   In this case I can make this  
![image](https://user-images.githubusercontent.com/94812921/143525020-1df0fc15-6ef4-42ae-85f2-912b086bceb6.png)
and set with the same data 
example:
```js

                    // set data
                    await this.candleSeries.setData(dataTemp);                    
                    await this.candleSeriesMACD.setData(dataTemp);
```
