### ISSUE TITLE
Shows 0 in price axis 

### ISSUE THREAD

**Issue by diamondhare** [tradingview/lightweight-charts#663] opened 2020-12-25 19:21 UTC
screenshot of my problem:https://snipboard.io/ZajLA1.jpg
data is provided properly from golang (array1)  i  checked logs
Update: It breaks with huge amount of data only but wish up to 20 works fine
My code:
                                                 `<script>
                                                    var chart = LightweightCharts.createChart(document.querySelector('#chart'), {
                                                        width: 400,
                                                        height: 406,
                                                    });
                                                
                                                    chart.timeScale().fitContent();
                                                    chart.applyOptions({ 
                                                        timeScale: {
                                                            barSpacing: 3,
                                                            fixLeftEdge: true,
                                                            lockVisibleTimeRangeOnResize: true,
                                                            borderVisible: true,
                                                            visible: true,
                                                            timeVisible: true,
                                                            borderColor: '#ffffff',
                                                            secondsVisible: true,
                                                        },
                                                        grid: {
                                                            vertLines: {
                                                                color: '#334158',
                                                            },
                                                            horzLines: {
                                                                color: '#334158',
                                                            },
                                                        },
                                                        priceScale: {
                                                            position: 'left',
                                                            mode: 2,
                                                            autoScale: false,
                                                            invertScale: true,
                                                            alignLabels: false,
                                                            borderVisible: false,
                                                            borderColor: '#555ffd',
                                                            scaleMargins: {
                                                                top: 0.30,
                                                                bottom: 0.25,
                                                            },
                                                        },
                                                        priceScale: {
                                                            borderColor: '#485c7b',
                                                        },
                                                        timeScale: {
                                                            borderColor: '#485c7b',
                                                        },
                                                        layout: {
                                                            textColor: '#ffffff',
                                                            fontSize: 11,
                                                            backgroundColor: 'transparent',
                                                        },
                                                    },);

                                                    var array1 = "{{.KlineBook}}";
                                                    array1 = array1.replace(/}/g, '},').slice(0,-2) + "]";
                                                    array1 = eval(array1)
                                                    console.log(typeof array1);
                                                    var candlestickSeries = chart.addCandlestickSeries();

                                                    candlestickSeries.setData(array1);

                                                    var array2 = "{{.AmountBook}}"
                                                    array2 = array2.replace(/}/g, '},').slice(0,-2) + "]";
                                                    console.log(array2);
                                                    array2 = eval(array2)
                                                    var volumeSeries = chart.addHistogramSeries();
                                                    volumeSeries.setData(volumeData);
                                                </script>`

**Comment by timocov** [comment] 2020-12-28 07:48
Duplicate of #594

**Closed by timocov** 2020-12-28 07:48 UTC
