### ISSUE TITLE
Set time scale in seconds or minutes

### ISSUE THREAD

**Issue by zeeshan-shabbir** [tradingview/lightweight-charts#1019] opened 2022-02-16 13:07 UTC
`
"data": [
  {
    "open": "1.18384",
    "high": "1.1845",
    "low": "1.18368",
    "close": "1.18429",
    "date": "2020-08-20 00:00:00"
  },
  {
    "open": "1.18458",
    "high": "1.18483",
    "low": "1.18367",
    "close": "1.18385",
    "date": "2020-08-19 23:00:00"
  },]
`
How to set this time data in graph ,, timescales in minutes or second .
When i set data with minutes, second this give year is undefined, if i set time in "2020-08-19" it set as per day .
I want to know if i can set my timescales in seconds.

**Comment by romfrancois** [comment] 2022-02-16 13:11
Question already answered on [SO](https://stackoverflow.com/questions/71121106/trading-veiw-lightweight-graph-set-timescale-at-one-hour/71142496#71142496)!

**Comment by timocov** [comment] 2022-02-16 13:12
Did you ever search similar issues/discussions before creating the issue? Please make sure that you searched for similar requests before hitting "new issue" button.

**Comment by timocov** [comment] 2022-02-16 13:12
Duplicate of  https://github.com/tradingview/lightweight-charts/discussions/642

**Closed by timocov** 2022-02-16 13:12 UTC

**Comment by zeeshan-shabbir** [comment] 2022-02-16 13:22
> Did you ever search similar issues/discussions before creating the issue? Please make sure that you searched for similar requests before hitting "new issue" button.

before asking question i search alot on but didnt find in the end i post here for help .

**Comment by zeeshan-shabbir** [comment] 2022-02-16 13:24
> Question already answered on [SO](https://stackoverflow.com/questions/71121106/trading-veiw-lightweight-graph-set-timescale-at-one-hour/71142496#71142496)!

thanks you are helping me great community
