### ISSUE TITLE
Allow specify color for every candlestick

### ISSUE THREAD

**Issue by ProgrammingLife** [tradingview/lightweight-charts#351] opened 2020-02-24 02:32 UTC
Is it possible to apply different colors for candlesticks? What about stepped vertical gradients for each candle? Is it hard to do?
I mean the gradient which consists of 10 different colors or so.
That could be very usefull for giving any additional information through the candle's body. It's like an individual heatmap for candlesticks.
What do you think guys?

**Comment by timocov** [comment] 2020-02-24 13:59
Did you see such options somewhere else?)

**Comment by ProgrammingLife** [comment] 2020-02-24 15:11
Actually, no. I think this is something new to the whole this world :)

**Comment by ProgrammingLife** [comment] 2020-02-26 06:28
Well, I tried to do it by myself but it looks it's not so easy as it seems :)
I thought I can pass a gradient data like this:
```
candlestickSeries.setData([
    { time: "2018-12-19", open: 141.77, high: 170.39, low: 120.25, close: 145.72, gradient: [[0.0, "red"], [0.5, "green"], [1.0, "blue"]] },
    ...
```
Firsly I tried to make change to Bar interface and add some new PlotValue but it looks it can be only number as a type so my attempt failed.

Then I tried to pass gradients data via options through the CandlestickStyleOptions patch:
```
export interface CandlestickStyleOptions {
	/** Color of falling candlestick wicks. Ignored if wickVisible == false or wickColor is specified */
	wickDownColor: string;

	gradients: Array<[Array<[number, string]>]>;
}
```
Looks the attempt is also not successful because I get error when I'm trying to pass through this interface such structure as **Array<[Array<[number, string]>]>**;
I can pass only: **Array<string>** but not two-dimensional array. Maybe I should replace DeepPartitial but I don't know how to properly do it.

Is there a way to pass two-dimensional array to candlestick-renderer.ts/_drawCandles() method?

**Comment by timocov** [comment] 2020-02-27 09:57
> Different colors for each candlestick 

I think this case is reasonable and we can mark it as feature request, but I'm not sure about "vertical gradients for coloring candles, heatmap". I think we can create another issue for that and continue the discuss there. What do you think @ProgrammingLife?

**Comment by ProgrammingLife** [comment] 2020-03-04 16:46
@timocov ok! :)

**Comment by timocov** [comment] 2020-03-06 08:02
Duplicate of #195.

**Comment by timocov** [comment] 2020-03-06 08:02
I just found that we already have such feature request :)

**Closed by timocov** 2020-03-06 08:02 UTC
Labels: enhancement, need proposal

**Comment by timocov** [comment] 2020-03-06 08:18
For gradient you might leave your suggestions in #185.
