### ISSUE TITLE
is it possible to block scroll for only one way? disable for to right?

### ISSUE THREAD

**Issue by srhtylmz19** [tradingview/lightweight-charts#532] opened 2020-07-25 01:18 UTC

**Comment by timocov** [comment] 2020-07-29 16:53
> disable for to right? 

How it should work? You can scroll to the left, but can't scroll back? 🤔

**Comment by srhtylmz19** [comment] 2020-07-29 16:57
i want to be able to scroll left (i mean able to see old data) but not right

**Comment by timocov** [comment] 2020-07-29 17:04
Duplicate of #218

**Closed by timocov** 2020-07-29 17:04 UTC
