### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by edmundss** [tradingview/lightweight-charts#1056] opened 2022-04-07 14:07 UTC
In example for `subscribeCrosshairMove` it says `subscribeClick`

![image](https://user-images.githubusercontent.com/9960319/162218201-789befc4-cf80-4cc0-b02c-2992c7b10372.png)

**Comment by edew** [comment] 2022-04-07 16:25
Thanks @edmundss 🔍 

Looks like this is a duplicate of #1054.

**Closed by edew** 2022-04-07 16:25 UTC
