### ISSUE TITLE
Changing time interval from daily to hourly

### ISSUE THREAD

**Issue by frevanauseloos** [tradingview/lightweight-charts#421] opened 2020-04-28 16:31 UTC
I'm using the candlestick chart example and I would like to change the time interval to the hourly chart, is this possible? My data is hourly.
https://jsfiddle.net/freva/y4xn8eta/2/

**Comment by timocov** [comment] 2020-04-30 15:38
Duplicate of #420

**Comment by timocov** [comment] 2020-04-30 15:38
Please don't create the same issues.

**Closed by timocov** 2020-04-30 15:38 UTC
