### ISSUE TITLE
There is a problem with the chart timestamp conversion time

### ISSUE THREAD

**Issue by gebilaofan** [tradingview/lightweight-charts#232] opened 2019-10-16 07:22 UTC
**Lightweight Charts Version:1.1.0** 

**Steps/code to reproduce:**

**Actual behavior:**
I am ready for the data, the timestamp is set to 1571210040 when setData in the chart, but there is a problem in rendering time.

The timestamp seems to be a problem when converting

**Expected behavior:**

**Screenshots**
![image](https://user-images.githubusercontent.com/46524158/66896722-fec19100-f027-11e9-9a91-84d08dbec5e3.png)
![image](https://user-images.githubusercontent.com/46524158/66896809-37fa0100-f028-11e9-8fe3-c55e17325f02.png)

**CodeSandbox/JSFiddle/etc link:**

**Comment by timocov** [comment] 2019-10-16 12:53
So, what the problem is?

**Comment by gebilaofan** [comment] 2019-10-18 02:11
> So, what the problem is?

https://github.com/tradingview/lightweight-charts/issues/232#issuecomment-542685473

**Comment by gebilaofan** [comment] 2019-10-18 02:11
> So, what the problem is?

I want to ask Is there an compatibility problem with Apple phones?

**Comment by gebilaofan** [comment] 2019-10-18 02:12
> So, what the problem is?

I do not know

**Comment by gebilaofan** [comment] 2019-10-18 02:23
> So, what the problem is?

Will it be a problem in the time zone?The time displayed in the picture differs from the current time by eight hours.

**Comment by timocov** [comment] 2019-10-18 08:39
> I do not know

I mean that you've said "There is a problem with the chart timestamp conversion time", but didn't say which one 🙂

> Will it be a problem in the time zone?The time displayed in the picture differs from the current time by eight hours.

I'm not sure that understand you correctly. On your screenshot on the timescale the latest time is `07:18`, the latest date you provided is `07:14` (I'm not sure, maybe there was a bit of realtime updates).

```
> new Date(1571210040000).toISOString()
'2019-10-16T07:14:00.000Z'
```

**Comment by gebilaofan** [comment] 2019-10-21 02:49
I used some demos on the official website, and I tried to change the time inside the data. https://jsfiddle.net/8efskn4y/
For example, 1571625180 is converted to time
![image](https://user-images.githubusercontent.com/46524158/67172975-df43b300-f3ef-11e9-99c2-234f96f2770f.png)
![image](https://user-images.githubusercontent.com/46524158/67173034-0c906100-f3f0-11e9-8d4a-50662af685a0.png)
There are eight time zones in the middle. I am Beijing time.
So, is it a time zone issue when the timestamp is converted?

**Comment by timocov** [comment] 2019-10-21 10:35
By default [we convert](https://github.com/tradingview/lightweight-charts/blob/d863263cddc611f4de987d5b7c15c2054f1ca9bf/src/model/time-scale.ts#L535-L541) dates as they are in UTC timezone, but you can override time formatter via `localizationOptions` (it'll affect crosshair mark only, not timescale marks thought).

**Comment by gebilaofan** [comment] 2019-10-22 06:51
> By default [we convert](https://github.com/tradingview/lightweight-charts/blob/d863263cddc611f4de987d5b7c15c2054f1ca9bf/src/model/time-scale.ts#L535-L541) dates as they are in UTC timezone, but you can override time formatter via `localizationOptions` (it'll affect crosshair mark only, not timescale marks thought).

Then will it be added later? When the timestamp is converted, the current time zone is automatically determined according to localization.

**Comment by timocov** [comment] 2019-10-22 10:07
> Then will it be added later?

What? Converting to specific timezone? Without supporting from the browser I don't think that we'll add it.

**Comment by timocov** [comment] 2019-11-20 09:07
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Closed by timocov** 2019-11-20 09:07 UTC
Labels: question

**Comment by saurabBajgain** [comment] 2019-12-03 04:37
@timocov  
please check this one:-
https://jsfiddle.net/saurab_93/ghc74Ldu/2/
![Capture_chart_img](https://user-images.githubusercontent.com/14971466/70020794-1b5e5c00-15c9-11ea-92a0-d706a32c4b57.PNG)

data i feed to chart is of dec 2 2019 as you can see in console but at chart it is ploting from dec 1 2019. 
do you have any idea how to ressolve this.... 
thankyou.

**Comment by saurabBajgain** [comment] 2019-12-03 05:57
> @timocov
> please check this one:-
> https://jsfiddle.net/saurab_93/ghc74Ldu/2/
> ![Capture_chart_img](https://user-images.githubusercontent.com/14971466/70020794-1b5e5c00-15c9-11ea-92a0-d706a32c4b57.PNG)
> 
> data i feed to chart is of dec 2 2019 as you can see in console but at chart it is ploting from dec 1 2019.
> do you have any idea how to ressolve this....
> thankyou. 

i solve this issue... !!!
https://jsfiddle.net/saurab_93/ghc74Ldu/15/

**Comment by timocov** [comment] 2019-12-03 16:28
@saurabBajgain Actually it isn't data of 2nd December

![image](https://user-images.githubusercontent.com/3112183/70069396-c3dce200-1602-11ea-86ae-17df0adfc6d1.png)

We use UTC value of the date:

```
>>> new Date(1575216000000).toISOString()
<<< 19:26:49.816 "2019-12-01T16:00:00.000Z"
```

If you want to see it as 2nd Dec, you need to add an alignment of the timezone for every bar you have.

**Comment by saurabBajgain** [comment] 2019-12-04 04:18
> @saurabBajgain Actually it isn't data of 2nd December
> 
> ![image](https://user-images.githubusercontent.com/3112183/70069396-c3dce200-1602-11ea-86ae-17df0adfc6d1.png)
> 
> We use UTC value of the date:
> 
> ```
> >>> new Date(1575216000000).toISOString()
> <<< 19:26:49.816 "2019-12-01T16:00:00.000Z"
> ```
> 
> If you want to see it as 2nd Dec, you need to add an alignment of the timezone for every bar you have.

yeah this method dateToChartTimeMinute() helps me  :-
function dateToChartTimeMinute(date) {
	return Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), date.getMinutes(), 0, 0) / 1000;
};

https://jsfiddle.net/saurab_93/ghc74Ldu/15/

Thankyou for your response
