### ISSUE TITLE
How to get  particular day line,histogram,candelstick color which is defined in data in subscribeCrosshairMove 

### ISSUE THREAD

**Issue by jadeja-rajdeep** [tradingview/lightweight-charts#1128] opened 2022-07-19 11:06 UTC
**Lightweight Charts Version:** 3.8

Hello guys 

i am adding different color based on some condition to candlestick bar and histogram bar for each day.

i am able to get that series options data using below line which return default values only.
`chartSeries[key].options()`

what i want is to get that day and previous days bar/line/histogram data with particular color that i set in data. when subscribeCrosshairMove  event is fired.

Thank you.

**Comment by SlicedSilver** [comment] 2022-08-26 18:37
Duplicate of #518 

The data obtained from the crosshairMove event won't exclude the colours, or additional properties on that data point.

If you are setting the colours for each data point within the data then you should be able to use the `time` property that the move event gives you to search your data set and find the source data point (which will contain the colour you set).

**Closed by SlicedSilver** 2022-08-26 18:37 UTC
