### ISSUE TITLE
Starting drawing a line incorrectly.

### ISSUE THREAD

**Issue by Altyair** [tradingview/lightweight-charts#329] opened 2020-02-12 13:18 UTC
Good day.
Help please.
Drawing a line does not start from the specified time stamp but from the beginning of drawing candles.
In the console you can see that the time of the input point is equal to 1580972400, but drawing a line starts with the time stamp 1580886000. 

The green marker indicates where the line should start, but the line starts where the candles begin.

Web site where you can see problem:
https://dev.charts.vobla.tech/g/tpslSignal?dark=true&dealPeriod=4&width=800&height=550&tsFrom=1580968800&tsTo=1580976000&symbol=BTCUSDT&type=short&timestamp=1580958000

below is a screenshot showing the problem:
![Снимок экрана от 2020-02-12 16-14-35](https://user-images.githubusercontent.com/18750140/74338240-39abb980-4dbb-11ea-9a66-c77a05684dd8.png)

**Comment by timocov** [comment] 2020-02-12 14:26
Can you provide jsfiddle example of the issue please?

**Comment by Altyair** [comment] 2020-02-12 15:25
is the website not enough?

https://dev.charts.vobla.tech/g/tpslSignal?dark=true&dealPeriod=4&width=800&height=550&tsFrom=1580968800&tsTo=1580976000&symbol=BTCUSDT&type=short&timestamp=1580958000

**Comment by timocov** [comment] 2020-02-12 16:58
> is the website not enough?

To see the issue - yes, but not for debug it. It contains minified code which freezes Chrome Devtools while beautifying, we can't load development build of the library and it contains a lot of your business logic we don't really need to have to analyze the issue. So, it'll _really_ helpful to have jsfiddle-like repro to debug it and don't spend the time for battle with these problems 🙂

**Comment by Altyair** [comment] 2020-02-12 19:12
reproduced the problem. 
the problem is observed in version 1.2.1. 
in version 1.0.0, it is not observed. 
jsfiddle version 1.0.0: https://jsfiddle.net/L7543z2r/ 
jsfiddle version 1.2.1: https://jsfiddle.net/fk089bL2/ 
the test data is the same here and there.

**Comment by timocov** [comment] 2020-02-13 07:54
Duplicate of #321

**Closed by timocov** 2020-02-13 07:54 UTC
