### ISSUE TITLE
Add option for lines with gaps

### ISSUE THREAD

**Issue by jussirantala** [tradingview/lightweight-charts#905] opened 2021-11-20 09:40 UTC
Hey,

**Problem**
In my use case I need to have gaps in the line-series lines because I have gaps in the data. I'm drawing trailing stop-loss line but the stop-loss isn't always in use. So if I want to use the same line-series for the same data, the old trailing stop-loss line will be joined to the new one creating a useless line which crosses all my charts. 

**Solution I'd like**
Possibility to have gaps in line-series data. For example by ending a line with _null_ data point.

**Comment by timocov** [comment] 2021-11-20 14:10
Please use search before open an issue: https://github.com/tradingview/lightweight-charts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+line+gaps

**Comment by timocov** [comment] 2021-11-20 14:11
Duplicate of #699

**Closed by timocov** 2021-11-20 14:11 UTC
