### ISSUE TITLE
Histogram Series overlap and hide smaller values (regression in 3.5.0)

### ISSUE THREAD

**Issue by jonluca** [tradingview/lightweight-charts#826] opened 2021-08-24 21:49 UTC
**Lightweight Charts Version:** 3.5.0

It worked in 3.4.0

**Steps/code to reproduce:**

Worked in https://codesandbox.io/s/lightweightchartsdemo-forked-5xq2p?file=/src/index.js

Does not work (same code) in https://codesandbox.io/s/lightweightchartsdemo-forked-qlg1u

**Actual behavior:**

The largest bar series on a given value overlaps the others, and covers up all smaller ones

**Expected behavior:**

The bars are rendered from largest in the back to smallest in the front

**Screenshots:**

**CodeSandbox/JSFiddle/etc link:**

Worked in https://codesandbox.io/s/lightweightchartsdemo-forked-5xq2p?file=/src/index.js

Does not work (same code) in https://codesandbox.io/s/lightweightchartsdemo-forked-qlg1u

**Comment by jonluca** [comment] 2021-08-24 21:49
@timocov I think this is related to the 3.5.0 release - it works as expected on the one right before it

**Comment by timocov** [comment] 2021-08-25 11:59
Duplicate of #812

**Closed by timocov** 2021-08-25 11:59 UTC

**Comment by timocov** [comment] 2021-08-25 12:06
This is intended behaviour, you need to change the order of creating series to make it work as you want.

Just updated the release notes to avoid further confusing https://github.com/tradingview/lightweight-charts/releases/tag/v3.5.0.

**Comment by jonluca** [comment] 2021-08-25 13:56
What if the bars alternate in tallest height? 

For instance, in series 1 the values go 0 10 5 and in series two they go 0 5 10, and we render series one first. 

Series two will completely overlap series 5 in that case.

There needs to be specific logic on each tick render to render them in order, by value, unless I'm misunderstanding that

**Comment by timocov** [comment] 2021-08-25 14:12
Actually, what is the difference between the two versions you provided? It seems that they are the same?

![image](https://user-images.githubusercontent.com/3112183/130806551-0c86331a-9872-4c7c-b1d1-ed9a35341404.png)

![image](https://user-images.githubusercontent.com/3112183/130806586-e957f284-ee1c-4d14-8b36-4f9b0d5d3418.png)

**Comment by jonluca** [comment] 2021-08-25 14:14
Ha, that's because I added a `hist.reverse()` to the not working link to confirm that it would work :) 

I just reset it - it should be back to "not working" - which is, as you said, just the order the series were added

**Comment by jonluca** [comment] 2021-08-25 14:14
<img width="2048" alt="Screen Shot 2021-08-25 at 9 58 23 AM" src="https://user-images.githubusercontent.com/13029040/130806965-ee86b9e5-bb54-4198-b092-15a8d470d10c.png">

**Comment by jonluca** [comment] 2021-08-25 14:15
<img width="947" alt="Screen Shot 2021-08-25 at 10 14 47 AM" src="https://user-images.githubusercontent.com/13029040/130807027-658cb4d8-fd5b-4c5a-aa61-760a191e0a6d.png">

**Comment by timocov** [comment] 2021-08-25 14:15
> Ha, that's because I added a hist.reverse() to the not working link to confirm that it would work :)

So, what the issue now is? 🙂

**Comment by jonluca** [comment] 2021-08-25 14:19
OK I just updated to a minimum viable example

https://codesandbox.io/s/lightweightchartsdemo-forked-qlg1u?file=/src/index.js:1877-1913

If you add two series that aren't strictly increasing, one of them will overlap

You can see that in the third datapoint, the blue line overlaps the red line. 

The order in which series are added is not guaranteed to be the ordering of values on the series. Histograms will overlap if the tallest one alternates

**Comment by jonluca** [comment] 2021-08-25 14:20
<img width="158" alt="Screen Shot 2021-08-25 at 10 20 01 AM" src="https://user-images.githubusercontent.com/13029040/130807903-74cfc48d-1ab7-4e97-8470-badff3d6e00b.png">

**Comment by timocov** [comment] 2021-08-25 15:22
> The order in which series are added is not guaranteed to be the ordering of values on the series. Histograms will overlap if the tallest one alternates

Yes. I think this was since the very first version and this works like that in all other our products (and probably in any other). What solution you see here?

**Comment by jonluca** [comment] 2021-08-25 15:25
I don't believe that's accurate - pretty much every charting library will render the bars at any given timepoint with the tallest in the back and the shortest in the front, otherwise overlapping bars aren't particularly useful.

The solution would be that, when you render a given time point, you order the charts at render time for that individual charts, not relying on the initial global sort. 

I can see how this might be difficult if the rendering logic isn't organized in a way that makes this easy, though.
