### ISSUE TITLE
Is there any way to retrieve the data from an already existing series?

### ISSUE THREAD

**Issue by thatman115** [tradingview/lightweight-charts#850] opened 2021-09-21 17:11 UTC
Currently I am using React-Redux to store the data I get from the websocket in the global state. This comes with a whole other number of issues and I was wondering if there is a more efficient way to retrieve my live data values. It is possible to `setData` to a series and `update` a series, is there a way to `getData` from the series?

**Comment by edew** [comment] 2021-09-22 09:41
Hi @thatman115.

More efficient in what way, is there a specific performance problem you're seeing?

I don't think we have a `getData` API that allows you to get the data you have added to a series.

**Comment by thatman115** [comment] 2021-09-22 09:46
Thanks for the response @edew.

When I call the `mapStateToProps` function to retrieve the chart data I have in the store, it prevents the `websocket` from connecting and therefore prevents the chart from rendering any data. I can't pinpoint why it is happening but I assume it is due to constant re-rendering or something like that.

I have tried to retrieve data from the series by accessing the different objects within the series, e.g. `series.Oe.Bi.Ae`, but the object response is quite messy and would require further parsing, it also doesn't contain any time data and I cannot guarantee that the data is in chronological order either.

A `getData` API would be really useful in my opinion, unless there is an alternative solution.

**Comment by timocov** [comment] 2021-09-22 13:50
Duplicate of #414

**Closed by timocov** 2021-09-22 13:50 UTC
