### ISSUE TITLE
add exact "value" position to SeriesMarkerPosition

### ISSUE THREAD

**Issue by club9822** [tradingview/lightweight-charts#912] opened 2021-11-22 08:36 UTC
**Is your feature request related to a problem? Please describe.**

 Currently there is `type SeriesMarkerPosition = 'aboveBar' | 'belowBar' | 'inBar';` for palcing marker on chart.
base on time/value (x,y), we wanna place marker on different locations by sending number value to position.
[base](https://github.com/tradingview/lightweight-charts/issues/127)

**Describe the solution you'd like**

value base position for SeriesMarkerPosition
[solution](https://github.com/tradingview/lightweight-charts/issues/127#issuecomment-857901447)

**Additional context**

![Capture5](https://user-images.githubusercontent.com/48531597/142828931-68c3ab10-402e-4b77-953c-7a314ac9f54a.PNG)

**Comment by timocov** [comment] 2021-11-22 10:26
Duplicate of #127

**Closed by timocov** 2021-11-22 10:26 UTC
