### ISSUE TITLE
is it possible to draw a line with a "gap" using lightweight-charts

### ISSUE THREAD

**Issue by okluoquan** [tradingview/lightweight-charts#1042] opened 2022-03-09 03:12 UTC
![屏幕快照 2022-03-09 上午10 48 33](https://user-images.githubusercontent.com/2103995/157365214-970beb7d-8beb-460e-b755-f75830f58c71.png)

where i draw ,i want to blank, not to join.

several separate series is not suitable.

**Comment by edew** [comment] 2022-03-09 09:05
@okluoquan You can try adding [whitespace](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/WhitespaceData) to your series data.

**Comment by timocov** [comment] 2022-03-09 09:16
It looks like a duplicate of #699?

**Comment by okluoquan** [comment] 2022-03-09 23:39
> @okluoquan您可以尝试在系列数据中添加[空格。](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/WhitespaceData)

thanks, but it seem not to  work

**Comment by okluoquan** [comment] 2022-03-09 23:43
> [它像#699](https://github.com/tradingview/lightweight-charts/issues/699)的副本？

thanks, it is what i find.

------------------------------------

demo：

const chart = LightweightCharts.createChart(document.body, { width: 400, height: 300 });
const lineSeries = chart.addLineSeries({
  lineType: 2,
} );

const data = [
    { time: '2018-12-03', value: 27 },
    { time: '2018-12-04', value: 27}, 
    { time: '2018-12-05', value: 27 },
    { time: '2018-12-06', value: null }, 
    { time: '2018-12-07', value: null}, 
    { time: '2018-12-08', value: 30 },
    { time: '2018-12-09', value: 30 },
    { time: '2018-12-10', value: 30 },
    { time: '2018-12-11', value: 30 },
    { time: '2018-12-12', value: 30 },
    { time: '2018-12-13', value: 30 },
];

lineSeries.setData(data);

----------------------------------------------

lib：

[lightweight-charts.standalone.production3.8.js.zip](https://github.com/tradingview/lightweight-charts/files/8218965/lightweight-charts.standalone.production3.8.js.zip)

**Closed** 2022-03-09 23:43 UTC
