### ISSUE TITLE
add Custom vertical Line not by LineSeries

### ISSUE THREAD

**Issue by zeeshan-shabbir** [tradingview/lightweight-charts#1049] opened 2022-03-23 10:41 UTC
is it possible we can show vertical line on time with no value required just line from up way to down in any graph (chandle bar area)graph? like vertical line on crosshair .
if not how to show vertical line?

**Comment by zeeshan-shabbir** [comment] 2022-04-02 13:58
waiting for response :-)

**Comment by SlicedSilver** [comment] 2022-08-26 16:16
Duplicate of #128, #127, and #965. Please post your suggestion there.

**Closed by SlicedSilver** 2022-08-26 16:16 UTC
Labels: question, duplicate
