### ISSUE TITLE
X axis scale with respect to time

### ISSUE THREAD

**Issue by pebblesbarrios** [tradingview/lightweight-charts#588] opened 2020-10-08 00:17 UTC
We are implementing a graph like the one in the image (Intraday), when validating with the development team we show that for the x-axis the same distance is shown between the three (3) moments of the operation delivered, for the example (9:11 am, 9:16 am, 9:17 am). It is possible that the graph adapts to the real time scale, that is to say that it is being built as time passes without necessarily delivering operations and that the distance between the points of the X axis is proportional in the defined time scale.
Example: The distance on the x-axis between the first 9:11 am operation and the second 9:16 is greater (Proportional) than the distance between the second 9:16 am operation and the third 9:17 am.

![image](https://user-images.githubusercontent.com/69873545/95401008-bacb3a00-08d1-11eb-8b9c-f0055e97b92f.png)

**Comment by timocov** [comment] 2020-10-08 07:35
Duplicate of #585

**Closed by timocov** 2020-10-08 07:35 UTC

**Comment by xrzhuang** [comment] 2022-01-08 04:06
pls add support for this
