### ISSUE TITLE
Zooming chart while new data is added changes visual range

### ISSUE THREAD

**Issue by bbenejc** [tradingview/lightweight-charts#998] opened 2022-02-01 22:48 UTC
**Lightweight Charts Version:** 3.7.0

**Steps/code to reproduce:** / **Actual behavior:**
I have a chart with data being "lazy loaded" when visible range changes enough. Once the data is loaded, it is added to the existing series using "setData".
Zooming the chart using the mouse wheel while the data is being added, causes the time scale to "jump", similar to what is described in #549  

**Expected behavior:**
The scale should not jump when new data is added, even if the chart is being scrolled / zoomed at the time.

**Screenshots:**
Below is link to a video of it happening.
https://user-images.githubusercontent.com/45341694/152061788-c4321a46-da99-4263-a271-321e216327b2.mp4

I pan the chart until it is at it's "edge" and start zooming in and out while the data is being loaded. It took multiple tries to demonstrate the bug. You can see it works well for the first 2 attempts, then the bug happens twice after that.

--

I am not sure if it is related, but zooming the chart while also panning it at the same time also appears buggy. Try holding your left mouse button and scroll the wheel while moving. The "anchor" point should stay fixed, but it does not.

**Comment by timocov** [comment] 2022-02-01 23:55
To be honest I didn't quite get your issue. Could you create a repro for this issue?

**Comment by bbenejc** [comment] 2022-02-02 09:07
Thank you for the response. After making a simplified example, I am unable to experience the bug with it. I'll have a deeper look into my original implementation where I noticed the bug and report back with what I find.

**Comment by bbenejc** [comment] 2022-02-02 10:37
I managed to create a simplified repro - here's the sandbox: 
https://codesandbox.io/s/998-repro-4ytcg

I am using react and in order to see this bug I had to use a state variable and update it inside the "subscribeCrosshairMove" handler.
Repro starts with a random chart of 1000 data points and it will add 10 to the left every second. In order to see the bug - position it so the left edge is visible and start scrolling up and down. Eventually you should notice the timestamp in the bottom jump by 10 seconds - video attached:
https://user-images.githubusercontent.com/45341694/152137841-04adf18a-1e64-4f70-a876-30ec4730e86a.mp4
It was easier to experience this on Firefox, but it happened on Chrome as well.

**Comment by edew** [comment] 2022-03-18 11:42
Hi @bbenejc.

Are you able to reproduce this issue without React?

**Comment by nejc0mins** [comment] 2022-03-21 14:27
No, I tried a couple different ways... but the simplest case I can reproduce it is by updating react's state variable in the subscribeCrosshairMove handler - as in the repro posted above.

**Comment by Effanuel** [comment] 2022-11-02 13:02
Experiencing the same issue if dragging the chart with mouse, during which, setData is called

**Comment by Effanuel** [comment] 2022-11-02 13:06
For reproducing, trigger setData inside subsribeToLogicalTimeRange if barsInfo.barsAhead is negative. Initially have the screen fully filled with candles, and then drag the chart with mouse to see ahead

**Comment by edew** [comment] 2022-11-07 12:57
@Effanuel are you using this library with React also?

**Comment by Effanuel** [comment] 2022-11-07 15:33
> @Effanuel are you using this library with React also?

Yes, but I dont think there should be any difference here

**Comment by SlicedSilver** [comment] 2023-02-09 15:52
Unable to reproduce this issue without using React, therefore it is most likely an integration issue with the framework which could be resolved within the React component.

**Closed by SlicedSilver** 2023-02-09 15:52 UTC
Labels: need more feedback, needs investigation, can’t repo
