### ISSUE TITLE
Vertical line markers

### ISSUE THREAD

**Issue by jonluca** [tradingview/lightweight-charts#965] opened 2022-01-05 19:10 UTC
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to designate series-independent events and markers. For instance, the fiscal quarter end dates that would apply to multiple series on a chart.

**Describe the solution you'd like**

Markers that are vertical lines on the page. They could be added to a given series or to a hidden series, or as native events on the chart.

**Additional context**

It would look something like this:

<img width="1844" alt="event lines" src="https://user-images.githubusercontent.com/13029040/148274813-d42bcc81-9db6-409f-8695-e1a61edff004.png">

**Comment by timocov** [comment] 2022-01-06 09:44
Duplicate of #128 and #127. Please post your suggestion there.

**Closed by timocov** 2022-01-06 09:44 UTC
