### ISSUE TITLE
"Cannot use import statement outside a module" error when importing lightweight-charts -> Vue + Nuxt

### ISSUE THREAD

**Issue by miketeix** [tradingview/lightweight-charts#557] opened 2020-09-01 18:01 UTC
**Lightweight Charts Version:**  3.1.5

**Steps/code to reproduce:**

Import lightweight-charts into your nuxt / vue project:

```
import { createChart } from 'lightweight-charts'
```
Node version: v12.13.1
Stack: Vue + Nuxt

**Actual behavior:**

Results in a runtime error: SyntaxError: Cannot use import statement outside a module
`node_modules/lightweight-charts/index.js:4:19`
which points to this code:
```
'use strict';

if (process.env.NODE_ENV === 'production') {
	module.exports = require('./dist/lightweight-charts.esm.production.js');
} else {
	module.exports = require('./dist/lightweight-charts.esm.development.js');
}

```
**Expected behavior:**
I'd expect there to be no issue with importing the library.

**Comment by timocov** [comment] 2020-09-01 19:23
Duplicate of #543

**Closed by timocov** 2020-09-01 19:23 UTC

**Comment by sankhaKarunasekara** [comment] 2021-04-04 18:40
If you want to get working light weight charts with Vue + Nuxt follow these steps,

1. create a plugin and add light weight chart to vue prototype

```
//plugins/lightweightcharts.js
import Vue from 'vue'
import * as LightWeightCharts from 'lightweight-charts';

Vue.prototype.$lwcCore = () => {
  return {
    LightWeightCharts
  }
}
```
2. add created plugin to `nuxt.config.js` with `ssr: false`
```
//nuxt.config.js
...
plugins: [
  ...
    {
      src: '~/plugins/lightweightcharts.js',
      ssr: false
    },
    ...
...
```

3. Use it inside the `mounted` in your Vue component

```
//yourComponent.vue
mounted: function () {
    let { LightWeightCharts } = this.$lwcCore()
    var chart = LightWeightCharts.createChart(self.$refs.stockPriceChart, {
      width: 600,
      height: 300,
      rightPriceScale: {
        scaleMargins: {
          top: 0.1,
          bottom: 0.2,
        },
...
```

hope it helps.

**Comment by ErfanBahramali** [comment] 2023-10-18 17:12
> For Nuxt 3 it is even simpler, just create a file named `charts.client.ts` in `plugins/`:
> 
> ```ts
> import { createChart } from 'lightweight-charts'
> 
> export default defineNuxtPlugin(() => {
>   return {
>     provide: {
>       charts: {
>         createChart
>       }
>     }
>   }
> })
> ```
> 
> In components you can use it like this:
> 
> ```
> <script lang="ts" setup>
> const container = ref<HTMLDivElement | null>(null)
> let chart
> 
> onMounted(() => {
>   const { $charts } = useNuxtApp()
> 
>   chart = $charts.createChart(container.value)
> }
> </script>
> ```

Hi
I tested this but it didn't work for me


**charts.client.ts:**
```ts
import { createChart } from 'lightweight-charts'

export default defineNuxtPlugin(() => {
  return {
    provide: {
      charts: {
        createChart
      }
    }
  }
})
```

**chart-tst.vue:**
```vue
<script setup>

const container = ref();
let chart;

onMounted(() => {

    const { $charts } = useNuxtApp()
    chart = $charts.createChart(container.value)
});
</script>

<template>
    <div ref="container"></div>
</template>
```

**Errors (In Inspect Console):**
![image](https://github.com/tradingview/lightweight-charts/assets/77061285/e2ae9ac9-9d8b-4fa1-8b3d-66527f25cb81)
