### ISSUE TITLE
Have a error tip in console when the chart has two series and it out of t  time range

### ISSUE THREAD

**Issue by qy20092011** [tradingview/lightweight-charts#388] opened 2020-04-03 06:57 UTC
**Lightweight Charts Version:**  1.2.2

**Steps/code to reproduce:**  
1. create one chart of two areaSeries
2. setData of two different array
3. move to left and out of the chart time range

**Actual behavior:** Have a error tip

**Expected behavior:** No error tip

**Screenshots** 
![image](https://user-images.githubusercontent.com/28330610/78332672-07e4f100-75bb-11ea-83b5-2b1fa8ebfe98.png)

**CodeSandbox/JSFiddle/etc link:** https://jsfiddle.net/qy20092011/xp5ndrv4/4/

**Comment by timocov** [comment] 2020-04-03 07:39
Duplicate of #373

**Closed by timocov** 2020-04-03 07:39 UTC
