### ISSUE TITLE
How to set up a 5 minute chart

### ISSUE THREAD

**Issue by hypo-thesis** [tradingview/lightweight-charts#477] opened 2020-06-13 21:44 UTC
I was wondering how I can set the time scale to 5 or 10 mins. I could not find the proper article in documentation.

**Comment by timocov** [comment] 2020-06-14 08:30
Duplicate of https://github.com/tradingview/lightweight-charts/issues/114#issuecomment-510468700

**Closed by timocov** 2020-06-14 08:30 UTC

**Comment by tankorsmash** [comment] 2020-10-16 23:54
I had a similar question about getting intraday on charts. Maybe it's worth adding an example to the docs somewhere prominent, I almost figured there wasn't any because there wasn't an obvious mention of it on the main readme.

**Comment by timocov** [comment] 2020-10-19 08:13
> does not, which is confusing because the error doesn't talk about mixing data types up.

@tankorsmash Yes, because business day could be presented in different formats like strings `YYYY-MM-DD` or an object with `year`, `month` and `day` fields in it, rather than "intraday" data must be unix timestamp. See https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md.

Also, see #315.
