### ISSUE TITLE
Facing issue with react-native Bundle Build

### ISSUE THREAD

**Issue by manojdp73** [tradingview/lightweight-charts#177] opened 2019-08-19 03:47 UTC
![Issue_with_react_native_bundle_build](https://user-images.githubusercontent.com/54257237/63237869-5a0e1780-c261-11e9-993a-5155dd51e276.PNG)
Hi,
Please help me with this issue faced during react-native bundle build
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 5.47 GB / 7.91 GB
  Binaries:
    Node: 10.16.0 - E:\Manoj\nodejs\node.EXE
    npm: 6.9.0 - E:\Manoj\nodejs\npm.CMD

Thanks and Regards,
Manoj Prithiani

**Comment by timocov** [comment] 2019-08-19 07:19
Why did you decide that the problem is with lightweight charts? I didn't even see it on your screenshot. Also, how we can help you if you don't provide steps to reproduce/repro repo?

**Comment by timocov** [comment] 2019-08-26 09:25
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Closed by timocov** 2019-08-26 09:25 UTC
Labels: out of scope, question
