### ISSUE TITLE
Area series fill should be towards the zero line

### ISSUE THREAD

**Issue by karanjitsingh** [tradingview/lightweight-charts#187] opened 2019-08-26 09:48 UTC
For area series with negative values, area fill should be towards the 0 line.

![image](https://user-images.githubusercontent.com/4632805/63681869-48ee7900-c814-11e9-9c65-0db7c00f057d.png)

If you see above, the area fill is basically from the line to the bottom of the chart. True area series should fill only till the zero-line, the full featured chart in trading view follows the same spec. 

Tradingview example:
![image](https://user-images.githubusercontent.com/4632805/63682070-b9959580-c814-11e9-9ead-8e6bb0ffcd46.png)

Is there anyway to do this?

**Comment by timocov** [comment] 2019-08-26 09:50
Duplicate of #151

**Closed by timocov** 2019-08-26 09:50 UTC
