### ISSUE TITLE
Unexpected horizontal line on mobile devices

### ISSUE THREAD

**Issue by pingustar** [tradingview/lightweight-charts#816] opened 2021-08-05 16:34 UTC
**Lightweight Charts Version:**
^3.4.0

**Steps/code to reproduce:**
```js
const seriesOptDefault: DeepPartial<LineStyleOptions & SeriesOptionsCommon> = {
  lineWidth: 1,
  crosshairMarkerVisible: false,
  priceLineVisible: false,
};

const chartOptDefault: DeepPartial<ChartOptions> = {
  layout: {
    backgroundColor: 'transparent',
  },
  crosshair: {
    vertLine: {
      visible: false,
    },
    horzLine: {
      visible: false,
    },
  },
  leftPriceScale: {
    visible: false,
    borderVisible: false,
  },
  rightPriceScale: {
    visible: false,
    borderVisible: false,
  },
  timeScale: {
    visible: false,
    borderVisible: false,
  },
  grid: {
    horzLines: {
      visible: false,
    },
    vertLines: {
      visible: false,
    },
  },
  handleScroll: false,
  handleScale: false,
};
```

**Actual behavior:**

An unexpected horizontal line below the chart is visible on mobile devices
![Screenshot 2021-08-05 at 18 28 05](https://user-images.githubusercontent.com/7262066/128387016-fb52732a-7709-49a1-a837-cf14b4bff562.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/7262066/128387239-252648af-1ab3-445e-b335-77dcd9ed46f6.png)

**Comment by lauris** [comment] 2021-08-17 16:38
I noticed similar issue when looking at chart from dev tools mobile view and setting scaling to less than 100%. However at least in my case the issue is not visible on real mobile devices.

100% scale (no axis lines):
<img width="476" alt="Screenshot 2021-08-17 at 19 34 45" src="https://user-images.githubusercontent.com/625264/129765495-acb490cd-4390-4139-a32e-bd8b8b9c9865.png">

Scaled (visible axis lines):
<img width="433" alt="Screenshot 2021-08-17 at 19 35 06" src="https://user-images.githubusercontent.com/625264/129765458-1cc7e481-f214-4722-9f3a-c42f01da31ea.png">

**Comment by timocov** [comment] 2021-08-18 09:36
@pingustar @lauris can anyone create a repro case for the issue pls?

**Comment by pingustar** [comment] 2021-08-23 09:21
@timocov sorry for the late response, was on vacation. Will create a repro case in the next few days ... will ping you here. 

Thanks!

**Comment by timocov** [comment] 2021-11-05 14:28
Since there is no updates so far I'm going to close the issue. If you'll have any question or updates - feel free to ping me.

**Closed by timocov** 2021-11-05 14:28 UTC
