### ISSUE TITLE
Time Scale is not working properly

### ISSUE THREAD

**Issue by ambrosio2506** [tradingview/lightweight-charts#585] opened 2020-09-28 23:41 UTC
We are using tradingView to chart equities behavior over time. Basically, when a equity price change we send it to the frontend of site, however we note that time scale is not working properly. So, if we send price at 9:30, and an update at  9:44, and another one at 9:50, we evidence time scale is the same, so, time interval appear in same scale (same space between three point in the X axis) Also, we evidence  trading view is not charting  the time between the 2 times.

**Comment by timocov** [comment] 2020-09-29 07:53
Duplicate of #483

**Closed by timocov** 2020-09-29 07:53 UTC

**Comment by timocov** [comment] 2020-09-29 07:55
Rephrased from [Stackoverflow answer](https://stackoverflow.com/a/62425499/3893439):

The `lightweight-chart` does know nothing about your data and what period they should have. If you'd like to have "smooth" time scale, you need to fill the gaps to make it in the way that distance between any 2 points are the same for all data points.

You can "fill the gaps" by using whitespaces and we'll "align" the time scale in that way.

**Comment by xrzhuang** [comment] 2022-01-08 04:06
pls add support for this, do you have any examples of "fill the gaps"?

**Comment by 0xAskar** [comment] 2023-01-27 04:14
any update on this would be great? my chart looks like this when i zoom out. the data is accurate, but the x-axis is not linear at all, spacing out one month and then jumping to next year. not sure why this happens while zooming out
<img width="514" alt="image" src="https://user-images.githubusercontent.com/37524379/215008046-7773c6ba-ec63-4db4-b1e9-93f4ed1dec33.png">
