### ISSUE TITLE
Missing data points are not handled consistency

### ISSUE THREAD

**Issue by dtanp** [tradingview/lightweight-charts#342] opened 2020-02-20 11:43 UTC
**Lightweight Charts Version:**
v1.2.1

**Steps/code to reproduce:**
https://jsfiddle.net/wg21qsaz/1/

On some dates, there is a data in only one series. However, on the same chart, data is synthesized on some days, while some days data is omit.

Here are dates that there is a data in one series only.
3-Dec => Missing point is omit (Expected)
8-Dec => Missing point is synthesized (Unexpected)
10-Dec => Missing point is omit (Expected)
15-Dec => Missing point is synthesized (Unexpected)
17-Dec => Missing point is omit (Expected)
22-Dec => Missing point is synthesized (Unexpected)
24-Dec => Missing point is omit (Expected)

**Actual behavior:**
Inconsistency behavior to manage missing data point.

**Expected behavior:**
If missing data point should be skipped or even better to provide option for users to choose to skip or use interpolation method.

**Screenshots**
There is no data on 15-Dec for blue series but chart created the data point.

![image](https://user-images.githubusercontent.com/5044988/74930497-56c23700-5410-11ea-997f-668c810425c1.png)

**Comment by timocov** [comment] 2020-02-20 11:49
Can you please test it with fixes from #330?

**Comment by timocov** [comment] 2020-02-21 09:12
Looks like it's fixed in #330.

**Comment by timocov** [comment] 2020-02-21 09:12
Duplicate of #321

**Closed by timocov** 2020-02-21 09:12 UTC
