### ISSUE TITLE
How to plot multiple lines in one chart?

### ISSUE THREAD

**Issue by hooshbartar** [tradingview/lightweight-charts#551] opened 2020-08-25 05:18 UTC
I am trying to plot two different charts(with different lenghth) using following code, but it doesn't work? 

    this.apiService.predictor(this.selectedStock ,this.startDay,this.endDay).subscribe((results) => {
      const lineSeries = this.chart.addLineSeries()

        for(let result of results[0]['prediction_value']) {
          console.log("the result1 is" , result);
          lineSeries.update({time : result.time , value : result.price})
        }
      const lineSeries2 = this.chart.addLineSeries()

        for(let result of results[0]['real_value']) {
          console.log("the result2 is" , result);

          lineSeries.update({time : result.time , value : result.price})
        }

The `result` arrays are something like below:

    the result1 is {price: 18, time: "2019-09-28"}
    the result1 is {price: 68, time: "2019-10-01"}
    the result1 is {price: 5, time: "2019-10-04"}
    the result1 is {price: 11, time: "2019-10-07"}
    the result1 is {price: 8, time: "2019-10-11"}
    the result1 is {price: 14, time: "2019-10-14"}

HOW CAN I PLOT 2 OR 3 LINES IN SAME CHART?

**Comment by timocov** [comment] 2020-08-25 16:59
Duplicate of #548

**Comment by timocov** [comment] 2020-08-25 16:59
Please don't spam the same issue. If we close the issue, it doesn't mean that we'll ignore comments there.

**Closed by timocov** 2020-08-25 16:59 UTC
