### ISSUE TITLE
Horizontal ribbon

### ISSUE THREAD

**Issue by glechic** [tradingview/lightweight-charts#890] opened 2021-11-12 14:52 UTC
Is there ability to fill horizontal area between, for example in simple case, static price lines like in the attached image
![image](https://user-images.githubusercontent.com/40598665/141486321-068b52b4-de7f-414b-9540-4c4456fde9f4.png)

**Comment by timocov** [comment] 2021-11-15 10:19
Duplicate of #140

**Closed by timocov** 2021-11-15 10:19 UTC
