### ISSUE TITLE
click event on desktop is normal, but click event on mobile is unavailable

### ISSUE THREAD

**Issue by cghbcf** [tradingview/lightweight-charts#1165] opened 2022-09-13 06:48 UTC
The subscribeClick event for Lightweight - Charts is normal on the desktop, but not on the mobile

**Comment by SlicedSilver** [comment] 2022-09-13 14:59
Could you please describe in more detail what the issue is with `subscribeClick`? 

If this is a bug report then please include the following sections: observed behaviour, expected behaviour, the version you are using, and the browser you are using (including the operation system).

**Comment by fhassis** [comment] 2022-11-05 19:52
I am having this issue as well in v3.8.0. This does not happen in v3.2.0.
The test was made with the example code snippet from the docs, in the browser (edge) on PC, and it works. But in Android and PC browser (with mobile device emulation) it did not work. On mobile I tested with edge, brave and chrome.

**Comment by SlicedSilver** [comment] 2022-11-05 23:49
Thanks. 
The bug has been fixed, and will be included in the next release of the library. 

If you require the fix now then you can clone the repo onto your machine and build the library using the following command:
```bash
npm run build:prod
```

See the [BUILDING.md](https://github.com/tradingview/lightweight-charts/blob/55d21262759ea1f0544bc8b35d7724c702660bcf/BUILDING.md) file for more information.

**Comment by SlicedSilver** [comment] 2023-02-08 13:28
This issue has been resolved with the [`v4.0.0`](https://github.com/tradingview/lightweight-charts/releases/tag/v4.0.0) release.

**Closed by SlicedSilver** 2023-02-08 13:28 UTC
Labels: upcoming fix
