### ISSUE TITLE
getVisibleRange throws exception

### ISSUE THREAD

**Issue by ololoepepe** [tradingview/lightweight-charts#630] opened 2020-11-28 12:00 UTC
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

Create a chart, add candlestick series, then call `getVisibleRange`:

```js
const chart = createChart(chartRef.current, {
  priceLineVisible: true
  // Some of the configuration omitted, as it is all about colors and fonts
});

const series = chart.addCandlestickSeries();

// This is called after some time as a reaction to a custom event, which is out of scope of this report
const range = chart.timeScale().getVisibleRange();
```

**Actual behavior:**

Exception is thrown, here is the stack:

```
TypeError: Cannot read property 'j' of undefined
  at bo(./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:131159)
  at getVisibleRange(./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:129892)
  at _addCandlesticks(./src/hooks/use-trading-view-chart.js:172:35)
  at _subscriptionCallback(./src/hooks/use-trading-view-chart.js:229:34)
  at callback(./src/hooks/use-trading-view-chart.js:166:12)
  at ? (./src/lib/api-provider.js:197:47)
  at Set.forEach(<anonymous>)
  at _handleNotificationCandlestick(./src/lib/api-provider.js:197:27)
  at _handleNotification(./src/lib/api-provider.js:148:5)
  at _handleMessage(./src/lib/api-provider.js:461:9)
  at WebSocket.A.onmessage(./src/lib/websocket-subscription-provider.js:99:12)
```

**Expected behavior:**

I expect getting a range object, or null, or whatever, but not an exception.

**Screenshots:**

This is how the chart looks like:

![This is how the chart looks like](https://user-images.githubusercontent.com/722991/100514844-d0eecb80-3199-11eb-9805-325e62028391.png)

**Comment:**

I was not able to reproduce this bug myself, but 4 of our users experienced it (captured with Sentry). One of the users had this about 2k times (yep, 2000+). He was using Chrome 86.0.4240 Windows 10.

I can't find any code changes to `getVisibleRange` method since 3.1.5, so 3.2.0 (current release) is probably affected, too.

**Comment by timocov** [comment] 2020-11-30 07:55
`bo(./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:131159)` is https://github.com/tradingview/lightweight-charts/blob/v3.1.5/src/api/time-scale-api.ts#L149, and the error `TypeError: Cannot read property 'j' of undefined` here might be thrown the only in case when you destroy chart first and then access to the timescale api (because we delete `_model` property in `destroy` https://github.com/tradingview/lightweight-charts/blob/v3.1.5/src/api/time-scale-api.ts#L34). So I'd say that you have some issues in your code regarding using chart object after it was removed, so you need to find this problem and fix it (after removing chart cannot be used in any way, it's "deleted").

> I can't find any code changes to getVisibleRange method since 3.1.5, so 3.2.0 (current release) is probably affected, too.

While upgrading to TypeScript 4.0 we removed code with deleting `_model` property from `TimeScaleApi` while destroying, so you won't get this issue in 3.2+ version, but the problem is still there and might case 1) memory leaks 2) wrong results (like you can get values from the old chart rather than from the new one).

Thus, I'm going to close this issue as soon as it's not related to the library itself, but if you have any questions - please ping me here.

**Closed by timocov** 2020-11-30 07:55 UTC
