### ISSUE TITLE
iPad - On activated crosshair chart moves instead of crosshair

### ISSUE THREAD

**Issue by florian-kittel** [tradingview/lightweight-charts#894] opened 2021-11-13 15:51 UTC
**Lightweight Charts Version:** 
3.8.0 (exists also in previous versions)

**Steps/code to reproduce:**
Any Chart with crosshair. Can be seen on example page as well.

**Actual behavior:**

(Tested with iPad Pro 11, iOS 14.8)
- Touch inside the example
- Crosshair is shows (as expected)
- Move finger 
- Chart is moving (not expected)

**Expected behavior:**

- Works on iPhone as expected (Tested on iPhone 12 pro with iOS 14.8 and iOS 15.1) but not on iPad
- Touch inside the example hand hold a second
- Crosshair is shows
- Move finger
- Crosshair is moving over the displayed chart
- Chart stays in place
- Touch and move directly
- No Crosshair is shown
- Move finger
- Chat is moved

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/10675435/141650138-92ec7046-9157-4fd1-83c1-bb01503e38d0.png)

**CodeSandbox/JSFiddle/etc link:**
https://de.tradingview.com/lightweight-charts/

or more specific
https://jsfiddle.net/TradingView/po7wzr69/

**Comment by timocov** [comment] 2021-11-15 10:24
@florian-kittel first of all, on the links you provided lightweight-charts is older version (v3.4 I guess). `3.8.0` is unpublished version (the latest version v3.7).

I'm not able to reproduce the issue, could you please record a video of the issue?

**Comment by florian-kittel** [comment] 2021-11-15 12:48
I have updated my project to master (3.8.0) to check if it is fixed, but is still present (also in 3.7.0). So the behavior you will see in your live examples as well (also if it is an older version).

iPad pro and Laptop with touchscreen (when using touch) has the wrong behavior. In mobile phone versions it is working, or better say the touch behavior on the chart works as expected. 

So in general when ever there is a crosshair, **there is space on the chart to move left or right because of additional data (e.g. when zooming)** and a user uses a touch device or touch screen (I think there is a behavior touch and drag, that differs from click and drag), when the user is pointing inside the chart, the crosshair is shown. When the user then move the finger left or right the hole chart is moving instead the crosshair. I can see that on iPad pro in my app with 3.8.0 and same in the examples of the public pages from tradingview (https://www.tradingview.com/lightweight-charts/).

So when I do that with my iPhone it is different. It is like the user expects it: touch inside the chart, crosshair is shown, moving fingers, moves crosshair instead of the chart. But I can deactivate crosshair by touching again to be able to move the chart. That is not working on iPad (pro) and Laptop (could be also a larger screen I guess) with touch screens.

Following is recorded by using finger touch on display at iPad pro / same at Laptop with Touchscreen (false behavior):
* Touch inside the chart
* Crosshair shown
* Touch move left or rigth
* Charts moves instead crosshair
![chart-touch](https://user-images.githubusercontent.com/10675435/141782070-a474192b-763f-46b3-9476-cbe5d901dfa2.gif)

This one is recorded on iPhone (expected behavior):
* Touch inside the chart
* Crosshair shown
* Touch move left or right
* Crosshair moves and not the chart
* Touch a second time
* Crosshair disapears
* Touch move left or right
* Charts moves as expected
* Touch a third time
* Crosshair appears (as expected)
* Touch move left or right
* Crosshair moves and not chart anymore
![chart-touch2](https://user-images.githubusercontent.com/10675435/141783423-7d345e1b-92d1-4237-a065-7701a91792df.gif)

**Comment by timocov** [comment] 2021-11-16 11:29
Thanks! That's because be default iPad (probably not all of them, but "big" versions at least) opens a "desktop" version of the website. If you request mobile version manually it will work fine I believe. The issue will be fixed in #106

**Closed by timocov** 2021-11-16 11:29 UTC
