### ISSUE TITLE
Add API to get chart values (data, markers, etc)

### ISSUE THREAD

**Issue by allartdo** [tradingview/lightweight-charts#414] opened 2020-04-22 11:49 UTC
Why is there no getPrice?
or getMarkers();

Would really like them, makes it much easyer for me to use.

Example:
This is how I need to get the current price now:
        `let currentPrice = Array.from(Array.from(priceArea._dataUpdatesConsumer.de.ee)[priceArea._dataUpdatesConsumer.de.ee.size - 1][1].mapping)[0][1].value;`

Just write getPrice(); would make it much more easyer and would have saved me at least 3 hours of searching.

**Comment by timocov** [comment] 2020-04-24 12:10
Why can't you store data somewhere in your code before passing it to series?

I just want to understand the case where it can be real issue.

Currently, we don't just store the data in series and use it everywhere. The data processed via our data-layer, which split that data and then convert to data series can understand. So, even if we can return the data back to you, it will be different type/array/etc. So I need to understand use case here.

**Comment by allartdo** [comment] 2020-04-24 13:20
Its not all issue's, its also a big time saver and userbility upgrades. Like I said, it took me 3 hours the get the current price in my chart. If you would have a build-in function that litirally does what I wrote in my in first commend but then the priceArea variable whould be changed to a lineSerie variable like the code below it would save other people alot of time.
```Javascript
/**
 * Returns the current value on the given line (yAxis).
 * 
 * @param {Object} lineSerie //Your line serie, in the image example: the green or blue line.
 */
function getCurrentValue(lineSerie) {
    return Array.from(Array.from(lineSerie._dataUpdatesConsumer.de.ee)[lineSerie._dataUpdatesConsumer.de.ee.size - 1][1].mapping)[0][1].value;
}
```
To make it more clear: you would get the value you see at the end of this line (or the label) and you can get it of the line you pass trough in the function. The lineSerie variable handles this. So in this case it would return -124.99 if you pass the green line, and -138.43 if you pass the blue line.

![image](https://user-images.githubusercontent.com/32697889/80212370-a81cbb80-8637-11ea-891d-c6630177f68e.png)
This is ofcourse just an example of how the get the current price, it might be so that you know a better way so feel free to change it.

If I look at a function like setMarkers(); then I think this is a very weird function which in my opinion does not work as great as I could imagine.

1. Why do you have to add all markers all over again when you want to implement just one?
2. Why is there only this setMarkers function and not a getMarkers function or getMarker?
3. Why is there no markers tab in the documentation? ATM its included in the series basics but in my opinion it should get its own tab since it has as good as nothing to do with the lineSeries, also if its programmed well enough (in a object oriented way) it could be placed anywhere. But this is a user preference.

**Issue**
You say this is a way of saving and using time in a chart.
![image](https://user-images.githubusercontent.com/32697889/80213105-f7afb700-8638-11ea-9413-539df3ffe9f4.png)
Source: https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md
But when I use this to add a marker, nothing shows up. Atleast, if I follow the documentation... Check this example:
```Javascript
greenLine.setMarkers([
   {
         time: 2020-4-22,            //This works, but adds a marker to the beginning of the line where the date/time is 2019-4-11.
         position: 'aboveBar',
         color: '#42f54b',
         shape: 'arrowDown',
         text: 'Current price: ' + movingAveragePrice,
         id: 'first',
   },
   {
         time: '2020-4-23',          //This does not work. And does not even show anything.
         position: 'belowBar',
         color: '#f54242',
         shape: 'arrowUp',
         text: 'Current price: ' + movingAveragePrice,
         id: 'second',
   }
]);
```
It might be just me doing something wrong but I didn't add such alot of weird things. Just used the normal functions of your library without any other library/plugin or anything included. If I indeed did nothing wrong (which I strongly think) then this is where the real ISSUE is comming to pass.

Also my code (above) does not look more different than in here:
![image](https://user-images.githubusercontent.com/32697889/80216379-401da380-863e-11ea-8eb4-b8cffe6b80e5.png)
Source: https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md

I hope this is enough feedback so far, I truly hope you add this soon, if you do and also make a single line have the posibility to have multiple colors I would go back to your library, but for now it just does not have the things I need. This library can do very much already but not if I talk about deep customization.

PS: if you see some bad english writings, sorry I have no autocorrect here and google translate makes it even worse :D

**Comment by scrwdrv** [comment] 2020-04-24 13:57
> ```js
> greenLine.setMarkers([
>    {
>          time: 2020-4-22,            //This works, but adds a marker to the beginning of the line where the date/time is 2019-4-11.
>          position: 'aboveBar',
>          color: '#42f54b',
>          shape: 'arrowDown',
>          text: 'Current price: ' + movingAveragePrice,
>          id: 'first',
>    },
>    {
>          time: '2020-4-23',          //This does not work. And does not even show anything.
>          position: 'belowBar',
>          color: '#f54242',
>          shape: 'arrowUp',
>          text: 'Current price: ' + movingAveragePrice,
>          id: 'second',
>    }
> ]);
> ```
> 
> It might be just me doing something wrong but I didn't add such alot of weird things. Just used the normal functions of your library without any other library/plugin or anything included. If I indeed did nothing wrong (which I strongly think) then this is where the real ISSUE is comming to pass.

Well, you basically did everything wrong in this part...

In your code, `2020-4-22` literally means `2020 - 4 - 22 = 1994`, which is an integer and will be considered as an [UNIX timestamp]( https://github.com/tradingview/lightweight-charts/blob/master/docs/time.md#unix-timestamp). And for the second marker, `'2020-4-23'` should be `'2020-04-23'` to follow the ISO format of `YYYY-MM-DD`.

Docs of lightweight-charts might not be great, but definitely good enough to make things running.

**Comment by allartdo** [comment] 2020-04-24 16:10
Im very sorry for what I said in that part. I see I indeed made a typo mistake...

I used and tested your answer but it seems to not make any difference. What I tested so far:

```Javascript
{
        // time: 1587852000,       // Unix timestamp | new Date('2020-04-26').getTime() / 1000 | not working :( ?????
        // time: '1587852000',     // ^^ But in string.
        // time: '2020-04-26',     // Not working, idk why.
        // time: '2020-4-26',      // Also not working, should be because of not having a 0 in front of 4 (month).
        // time: 2020-4-26,        // Shows only at the beginning of a line. This confuses me the most...
        // time: new Date('2020-04-26').getTime() / 1000,  // Not working.
        // time: new Date('2020-4-26').getTime() / 1000,   // Not working.
        // time: day1,             // Not working.
        // time: day2,             // Not working.
        // time: day3,             // Not working.
        // time: day4,             // Not working.
        // time: 1,                // Shows only at the beginning of a line.
        // time: 12,               // Shows only at the beginning of a line.
        // time: 123,              // Shows only at the beginning of a line.
        // time: 1234,             // Shows only at the beginning of a line.
        // time: 12345,            // Shows only at the beginning of a line.
        // time: 123456,           // Shows only at the beginning of a line.
        // time: 1234567,          // Shows only at the beginning of a line.
        // time: 12345678,         // Shows only at the beginning of a line.
        // time: 123456789,        // Shows only at the beginning of a line.
        // time: 1234567890,       // Shows only at the beginning of a line.
        // time: 12345678901,      // Not working.
        // time: 123456789012,     // Not working.
        // time: 1234567890123,    // Not working.
        position: 'aboveBar',
        color: '#42f54b',
        shape: 'arrowDown',
        text: 'Current price: ' + movingAveragePrice,
        id: 'first',
},
```
My chart begins at: 2019-03-20 and stops at: 2100-04-22. From this current date till 2021-current month-current date. So thats one year with a new line each day. I actually got an error message when trying the second, time: value. the unix timestamp in a string. Error:
![image](https://user-images.githubusercontent.com/32697889/80229855-597c1b00-8651-11ea-8a8f-471cb418c793.png)
Seems it indeed needs the yyyy-mm-dd and if I think about it. If you want to draw a chart from year 1 or maybe even 0 or below. Then that should be possible aswell right? And should then the mm and dd not count for the same? Then my typo with the missing 0 in front of the 4 should not matter that much. 

I also tested this and I see that year 999 and 99 works but when I go to year 9 or below it stops working. Did not test a year like 100 or 10 or 50. In date format this was:

```Javascript
'999-4-24' //Working
// And
'99-4-24' //Working
// And
'9-4-24' // Not working
```

Looking forward to see a new answer.  :D

**Comment by scrwdrv** [comment] 2020-04-24 16:41
> I used and tested your answer but it seems to not make any difference. What I tested so far:

https://jsfiddle.net/nLsouf74/2/
It works for me.

> So thats one year with a new line each day. I actually got an error message when trying the second, time: value. the unix timestamp in a string. Error:
> ![image](https://user-images.githubusercontent.com/32697889/80229855-597c1b00-8651-11ea-8a8f-471cb418c793.png)

Comes to UNIX timestamp, you need to use `number` instead of `string`.

**Comment by allartdo** [comment] 2020-04-24 19:14
Okey so this is what I have:
https://jsfiddle.net/98x2q54s/1/
@scrwdrv Can you see what goes wrong because I dont understand it anymore :(

I hope u understand what I did btw because my code did get kinda messy after getting frustrated by things not working like I wanted it to work. Usually I cleanup after I fix my issue but now I just can't figure it out anymore. I also did remove some parts since they are not having anything todo with the issue, so unused variables or code might be still there.

It might look like this goes oftopic but it might go back ontopic. If I made an mistake again it probably won't go ontopic and there would be nothing wrong with the setMarkers() thing then it would.

**Comment by scrwdrv** [comment] 2020-04-24 20:07
https://jsfiddle.net/nk0412pu/

Again, you should use `number` at series' value, `toFixed()` function returns a `string`, obviously it's not gonna work. If you really wanna round up your numbers, try `Math.round() instead`.

No offence, but I think your major problem is with javascript, you don't seem to understand the primitive type and having a lot of trouble writing your code in an efficient way. Thus, many of your issues might be caused by that instead of this library. 

This is kind of off topic I assumed. Yet I suggest you write in Typescript (which is a superset of javascript) to check these potential errors, since this library is written in Typescript the first place and it will very much improve your coding experience by providing better code completion and type checks.

**Comment by allartdo** [comment] 2020-04-25 12:27
You may want to read what I said in here: #362 

> No offence, but I think your major problem is with javascript, you don't seem to understand the primitive types and having a lot of trouble writing your code in an efficient way. Thus, many of your issues might be caused by that instead of this library.

I know im not great, but I already told you that. 

> I hope u understand what I did btw because my code did get kinda messy after getting frustrated by things not working like I wanted it to work. Usually I cleanup after I fix my issue but now I just can't figure it out anymore. I also did remove some parts since they are not having anything todo with the issue, so unused variables or code might be still there.


You suggest I use Typescript while the library tells me [Javascript is what I should use](https://github.com/tradingview/lightweight-charts/tree/master/docs).
![image](https://user-images.githubusercontent.com/32697889/80279570-da452080-86fe-11ea-8829-7dfd523b0595.png)
I understand Typescript has its pros and cons but I want to keep things as general as it is. Javascript people must be able to do this and Typescripters aswell (if thats a word :P).

I dont really understand why using a string in the price part has something to do with setting a marker. I need to pass the TIME coordinate to tell it where to place, not the price coordinate right? And I understand this is made in Typescript, and you say its strict in using variables, but then why use Javascript as an example? For typescript this would, I assume, not be a problem but for Javascript it is. Also in the documentation there is nothing telling me I HAVE to use a number instead of a string, and if I use a string its not giving me any error or waring.
![image](https://user-images.githubusercontent.com/32697889/80279878-7facc400-8700-11ea-9ff3-e11969ac2353.png)

But all comming to one, I am very happy you helped me. I again understand more and more now. And thats what I like. 👍

**Comment by Tucsky** [comment] 2020-04-25 12:42
Data getter would be nice indeed. The values are there, if we can get them by digging into the _dataUpdatesConsumer object I don't see why getters for easier access wouldn't be possible ?

**Comment by scrwdrv** [comment] 2020-04-25 13:17
> You suggest I use Typescript while the library tells me [Javascript is what I should use](https://github.com/tradingview/lightweight-charts/tree/master/docs).
> ![image](https://user-images.githubusercontent.com/32697889/80279570-da452080-86fe-11ea-8829-7dfd523b0595.png)
> I understand Typescript has its pros and cons but I want to keep things as general as it is. Javascript people must be able to do this and Typescripters aswell (if thats a word :P).

This is a Javascript library written in Typescript, as your screenshot mentioned:
> Note: the package is shipped with TypeScript declarations, so lightweight-charts can be easily used in TypeScript code.

I think it's fair to say that Typescript is recommended but not needed. But it is more common to do examples in Javascript since Typescript always compiled to Javascript to run, and developers of Typescript are surely capable of understanding Javascript.

> Also in the documentation there is nothing telling me I HAVE to use a number instead of a string, and if I use a string its not giving me any error or waring.
> ![image](https://user-images.githubusercontent.com/32697889/80279878-7facc400-8700-11ea-9ff3-e11969ac2353.png)

Yep, I agree it should throw an error or something. 

But I think it is very much a common sense that a value should be numeric type (number, integer, float, etc.) in most of programming languages. Not to mention the example uses `number` as well, it's pretty clear that `number` is the type to go with.

**Comment by timocov** [comment] 2020-04-27 19:11
> Why do you have to add all markers all over again when you want to implement just one?

As I said in other issue the reason is simple - no one asked for that.

> Why is there only this setMarkers function and not a getMarkers function or getMarker?

@allartdo and here the same - 1) no one asked it before 2) you're who provides the data, we need to have strong reasons to provide them back and need to understand in what way/format we need to return them. We process the data internally and their structure might be changed.

> Why is there no markers tab in the documentation? ATM its included in the series basics but in my opinion it should get its own tab since it has as good as nothing to do with the lineSeries, also if its programmed well enough (in a object oriented way) it could be placed anywhere. But this is a user preference.

PRs are welcomed. If you think that you now how it should be friendly for an user - please help us make it better with your suggestions in a PR. I think it's the best you can make here instead of telling that "this shouldn't be here, this isn't described well" and so on. It's open-source and every member of the community can make it better. I've thought that works in this way, am I wrong?

> You suggest I use Typescript while the library tells me Javascript is what I should use

We don't force you use TypeScript because it's the only your choice what you'd like to use in your project. We personally prefer to use TypeScript in our projects. But we made our examples in JavaScipt because we understand that there is someone who don't use or even don't know about TypeScript, why we should force it to use TypeScript instead? The library is aimed to JavaScript project, but if you'd like to use TypeScript - we provide type declarations for you so you don't need to worry about that.

> I think it's fair to say that Typescript is recommended but not needed. But it is more common to do examples in Javascript since Typescript always compiled to Javascript to run, and developers of Typescript are surely capable of understanding Javascript.

Yes, exactly!

> For typescript this would, I assume, not be a problem but for Javascript it is. Also in the documentation there is nothing telling me I HAVE to use a number instead of a string, and if I use a string its not giving me any error or waring.

[Series-basics page has Data section](https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md#data) where said the following:

> Every series has its own data type. Please refer to series page to determine what type of data the series uses.

That means, that you find what type of the data you need to use to provide it to the series' methods setData/update. And then, every series' type page in the docs has "Data format" section where described a type of data item:

- https://github.com/tradingview/lightweight-charts/blob/master/docs/line-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/area-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/candlestick-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/candlestick-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/bar-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/histogram-series.md#data-format
- https://github.com/tradingview/lightweight-charts/blob/master/docs/ohlc.md

And there you can find `time` property which leads to time page:

![image](https://user-images.githubusercontent.com/3112183/80410160-d1a54380-88d2-11ea-84ee-0e6f42e615b2.png)

Did you see that or you just scroll to examples without even reading that? Series-basics page has definition of the common methods like `setData` and `update` because such methods are common for every type of series (it's kind of API references mixed with docs). But anyway, if you understand how to make it better - please send your PR.

> Yep, I agree it should throw an error or something.

And I agree too - see https://github.com/tradingview/lightweight-charts/issues/315.

----

@scrwdrv thanks!

**Comment by mattou78400** [comment] 2020-09-03 12:32
Hello,

I was indicated to post my thoughts/questions here

Its incredibly frustrating to pull the candles drawn on the chart instance

Describe the solution you'd like

The best would be to have a function returning displayedCandles(chartInstance) -->
[
{timestamp: XXX,
open: XXX
high: XXX
low: XXX
close: XXX}
...]

Additional context

this is how I currently do it but it seems to be browser specific and not portable
for (let serie of chart.activeSeries) { if (serie.id == 'price'){ for (const k of chart.getSerie(serie.id).api.G_.ed.V_.keys()) { if (k.ui == -1){ for (let candle of k.G.ma){ if (candle.V.Ss >= (visibleRange.from-this.timeframe*31)) displayedCandles.push({ timestamp : candle.V.Ss, open : candle.Z[0], high : candle.Z[1], low : candle.Z[2], close : candle.Z[3], }) } } } } }

Why this would be useful:
-> when both live candles and cached candles are being drawn, it would be easier to consider drawn candles rather than recomputing the shown cached candles + last candle
Especially considering some calculation might want to consider past data/candles

I hope this makes sense.
Thanks

**Comment by averinpro** [comment] 2021-10-07 22:36
Of course, this is very convenient. Add your own string to TradingView, write it to your own array to clear this array every 10 seconds and create a new one. Since TradingView cannot assign to it, which after 10 seconds can be simply corrected or deleted. As a result, to get the current price, we just have to connect to stream a second time :) very convenient

**Closed** 2021-12-15 14:34 UTC
Labels: enhancement, breaking change
