### ISSUE TITLE
2D Markers (with value and point in time specified)

### ISSUE THREAD

**Issue by canselcik** [tradingview/lightweight-charts#566] opened 2020-09-09 19:44 UTC
**Is your feature request related to a problem? Please describe.**

As it stands it seems we can create markers but these markers can be inBar, aboveBar or underBar. If I wanted to put a marker on a certain value right above where the candle closed on a certain point in time, there is no way to achieve that as far as I can tell. We also need to put it exactly where the candle is, otherwise markers don't work. This second point is not that limiting but the former is.

**Describe the solution you'd like**

2-dimensional markers with value and point in time specified. Ideally providing flexibility on the time value being anywhere (even outside a candle) but even if just a "value" (y-axis) is supported in the current Marker API, it would be very useful.

**Comment by timocov** [comment] 2020-09-10 16:40
Duplicate of #127

**Closed by timocov** 2020-09-10 16:40 UTC
