### ISSUE TITLE
Draw lines that does not affect Price Scale

### ISSUE THREAD

**Issue by tolotrasamuel** [tradingview/lightweight-charts#396] opened 2020-04-07 17:27 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there is no API that allows drawing a line between two points which does not affect the price scale. These lines could be used as price levels, extra visuals, trendline...
The workaround I found is to draw a line series with only two points. Here is an example:

```
const lineSeries2 = chart.addLineSeries();
lineSeries2.setData([
    { time: '2018-11-20', value: 300 },
    { time:  '2019-05-24', value: 300 },
    
]);
const lineSeries = chart.addLineSeries();
lineSeries.setData([
    { time: '2018-11-20', value: 173 },
    { time:  '2019-05-24', value: 173 }
]);
```
Here is the [jsfiddle](https://jsfiddle.net/doL1vsgj/3/) code.
The problem is that the line series affects the price scale when you auto-scale.

![image](https://user-images.githubusercontent.com/29230303/78700034-e0bd5500-7915-11ea-9ef1-d165afe6b04c.png)

The blue lines are the lines that I want to add.

This is unwanted because by changing the price scale, these lines makes the actual series (ohlc) hard to read.

The expected behavior is as follow:

![image](https://user-images.githubusercontent.com/29230303/78700122-02b6d780-7916-11ea-8cc9-3ad969f2d584.png)

The upper blue line can only between by manually changing the price scale or dragging the chart up.
The lower blue line just happened to be visible because it inside the candle price range

I found something similar already existing which is the `overlay` propriety but unfortunately, it creates a completely new price scale for the series. ( I do not know if that is the expected behavior or it's a bug but it produces something really messy )
![image](https://user-images.githubusercontent.com/29230303/78699979-ca16fe00-7915-11ea-8b03-a553fb808c31.png)

**Describe the solution you'd like**

I propose either of two solutions:

1) Add an option `userSamePriceScale` to `OverlaySeriesSpecificOptions`

```
export interface OverlaySeriesSpecificOptions {
	overlay: true;
	scaleMargins?: PriceScaleMargins;
        useSamePriceScale: boolean; // Add this
}
```

This would force the overlay to use the same price scale as the non-overlay series already added , not create its own

2) Create a new type of API called `DrawingsApi` or something like.
It would be extended with `LineDrawing` or `CircleDrawing`.
And it would be added on the ChartApi as follow:

```
const lineDrawing = chart.addLineDrawing({
    from:{ time: '2018-11-20', value: 173 },
    to: { time: '2019-11-20', value: 173 },
});
```
        

**Additional context**

**Comment by timocov** [comment] 2020-04-07 19:51
Looks like duplicate of #334. May I ask you to post your suggestion there instead please so we can close it in favor to that issue?

**Comment by timocov** [comment] 2020-04-08 14:36
Thank you!

**Closed** 2020-04-21 15:16 UTC
