### ISSUE TITLE
Is there any way i can draw a dotted line on line chart in vertical axis 

### ISSUE THREAD

**Issue by LovePareek** [tradingview/lightweight-charts#1230] opened 2022-12-28 06:52 UTC
I'm looking for a vertical line and attempting to create a pointer at the edge of the data where it's running in real-time using a lightweight chart. I searched the documentation but couldn't locate one; is there a way I can add a vertical dotted line like the one in the image I've shared?

[image](https://imgur.com/XdxMkqV)

**Comment by romfrancois** [comment] 2022-12-28 17:25
Duplicate of [693](https://github.com/tradingview/lightweight-charts/issues/693)

**Closed by romfrancois** 2022-12-28 17:25 UTC
