### ISSUE TITLE
TypeError: createChart is not a function

### ISSUE THREAD

**Issue by bi305** [tradingview/lightweight-charts#927] opened 2021-12-07 09:17 UTC
I am  using  next.js
when  ever  Import createChart form  lightweight-charts it  give  me  error 
Server Error
Syntax Error: Cannot use import statement outside a module 
  
but  when  I  import it like  this
const createChart = dynamic(() => import('lightweight-charts'));
I  gives me  the  error of
Reference Error: document is not defined
then  if  I  resolve this i  got  the  error  createChart  is  not  function
![image](https://user-images.githubusercontent.com/72016671/145001205-4a1c7311-29f3-4345-b4bf-650e65dd696d.png)

**Comment by timocov** [comment] 2021-12-07 09:27
Duplicate of #488

**Closed by timocov** 2021-12-07 09:27 UTC
