### ISSUE TITLE
How to give a single line serie multiple colors with Tradingview Lightweight charts in Javascript?

### ISSUE THREAD

**Issue by allartdo** [tradingview/lightweight-charts#412] opened 2020-04-22 10:09 UTC
I think it should be a common thing to change the color of a line series for each new created part of a line. This url explains my issue.
https://stackoverflow.com/questions/61349463/how-to-give-a-single-line-serie-multiple-colors-with-tradingview-lightweight-cha

Im kinda new to this github issue reports, please explain if I do something wrong.

**Comment by timocov** [comment] 2020-04-22 12:18
Duplicate of #195

**Closed by timocov** 2020-04-22 12:18 UTC

**Comment by allartdo** [comment] 2020-04-22 12:30
So if I understand correctly, you want me or someone else to dive into your code and fix the not dynamic code? I did this to get the price of the last added line... In 3 hours. I would need 50 euro per hour to do that for customers... Sorry if im wrong ¯\_(ツ)_/¯

**Comment by timocov** [comment] 2020-04-22 12:49
It's open source, if you'd like to add this feature asap, you can do it yourself and provide PR with fixes (but before that we need to get proposal first in the original issue). If you don't want to/can't fix it, you can subscribe to original issue and wait until it'll be closed so that means it's fixed.

**Comment by timocov** [comment] 2020-04-22 16:04
@allartdo may I ask you to copy that feedback to https://github.com/tradingview/lightweight-charts/issues/362 please? We collect all feedback there and I think it's good candidate to be there.

**Comment by allartdo** [comment] 2020-04-22 16:49
I will!

**Comment by allartdo** [comment] 2020-04-22 16:56
Hmm I see I somehow opened the issue again? Guess thats because I used a link in the feedback part?
