### ISSUE TITLE
Scatter chart

### ISSUE THREAD

**Issue by yarshad** [tradingview/lightweight-charts#365] opened 2020-03-04 21:49 UTC
Is it possible to create a simple scatter chart without a line, and only showing data points like you can do in excel. I looked at the markers but you cannot specify both x and y coordinates for it.

 
![image](https://user-images.githubusercontent.com/8764008/75926192-1c0cc580-5e38-11ea-997c-9a95ca335020.png)

**Comment by timocov** [comment] 2020-03-05 08:19
No, currently it's impossible. Did you see such type of chart in any other trading charting solution?

**Comment by yarshad** [comment] 2020-03-05 15:08
I have seen it in highcharts/highstocks

**Comment by timocov** [comment] 2020-03-06 07:46
I guess it's kind of duplicate of #127.

**Comment by johanwasserman** [comment] 2022-12-15 04:56
@timocov
this is important to add a parabolic SAR, for example.
![image](https://user-images.githubusercontent.com/7691625/207775657-84a51759-1356-472c-8ad8-8f7aef5b5f84.png)

I am willing to contribute to the project.  I need to add this scatter plot as well as upper and lower bands with fill between on a chart.  I also need to add capabilities like bollinger bands for example.

Who can help to fastrack me on the code structure etc?  It will take me some time to figure it out by myself.  Just getting to understand it would be very helpful.

**Comment by romfrancois** [comment] 2022-12-15 12:16
Hi @johanwasserman !
That's something we could actually work on. Can't promise any ETA but will check with the team and will update this ticket accordingly.

**Comment by 0xAskar** [comment] 2023-01-27 06:31
any updates on possibly adding scatter data?

**Comment by romfrancois** [comment] 2023-01-27 06:40
Not yet no; when we'll have an update we'll update this ticket.

**Comment by zccz14** [comment] 2023-04-16 10:33
> 

+1, I met this on PSAR indicator.

**Closed** 2023-06-13 12:29 UTC
Labels: enhancement

**Comment by bigtotamoboss** [comment] 2026-03-25 01:06
Hi. Any updates?
