### ISSUE TITLE
have the time scale automatically scaled to 100% width

### ISSUE THREAD

**Issue by krtschmr** [tradingview/lightweight-charts#229] opened 2019-10-10 07:43 UTC
regardless if i have only 10 datapoints or 150, there should be an option that renders all datapoints into the visible chart area.

currently we need to hope that we have correct amount of data points for the last 24 hours and then play with timeScale.barSpacing to make it fit to the whole width
![image](https://user-images.githubusercontent.com/13366714/66548794-261de700-eb6c-11e9-90f8-5d150432f2f3.png)
![image](https://user-images.githubusercontent.com/13366714/66548826-3209a900-eb6c-11e9-95ac-b0f0433d3b18.png)

it's the same data for both graphs, just different bar spacing. would be awesome to simply ignore whatever settings and just render all datapoints into the full width.

**Comment by eugene-korobko** [comment] 2019-10-10 08:29
Hello!

Please check `fitContent` function

Example is [here](https://jsfiddle.net/TradingView/4pd5j8xa/)

Documentation is [here](https://github.com/tradingview/lightweight-charts/blob/master/docs/time-scale.md)

**Comment by krtschmr** [comment] 2019-10-10 10:25
@eugene-korobko 

it seems to be slightly broken. with `fitContent` i alwayts have these nasty borders left/right which are not really borders, the charts just don't draw there.

![image](https://user-images.githubusercontent.com/13366714/66561018-ced74100-eb82-11e9-8f3b-19825008defe.png)

**Comment by krtschmr** [comment] 2019-10-10 10:38
```
  const canvas = $("#charts .chart."+coin)[0]
  var chartOptions = { height: 175, width: canvas.offsetWidth }

  var chart = LightweightCharts.createChart(canvas, chartOptions);
  const areaSeries = chart.addAreaSeries({
    topColor: 'rgba(67, 141, 255, 0.05)',
    bottomColor: '#e8edf8',
    lineColor: '#438dff',
    lineStyle: 0,
    lineWidth: 2,
    crosshairMarkerVisible: true,
    crosshairMarkerRadius: 10,
    overlay: false,
    priceLineVisible: false
  });

  chart.applyOptions({
      handleScroll: { mouseWheel: false, pressedMouseMove: false, horzTouchDrag: false, vertTouchDrag: false },
      handleScale: { axisPressedMouseMove: false, mouseWheel: false, pinch: false, },
      timeScale: { barSpacing: 1, visible     : false },
      priceScale: { position: 'none', borderVisible: false,scaleMargins: { top: 0.2, bottom: 0.05,}},
      grid: { vertLines: { visible: false,}, horzLines: { visible: false} },
      crosshair: { vertLine: { visible: false, }, horzLine: { visible: false} },
  });
```

**Comment by deantheiceman** [comment] 2019-10-12 02:54
Were you able to fix this? I'm getting this same error too

**Comment by krtschmr** [comment] 2019-10-12 02:55
@deantheiceman  not yet. my only fix is kina like to render more data points. we use influx and i say last 24hours with 15 minute timings and the problem is there. if i say last 30 hours with 15 minutes it's fixed

**Comment by kirchet** [comment] 2019-10-14 17:17
We have a restriciton for the maximum bar spacing (the distance between two bars), maybe we should increase its value

**Comment by krtschmr** [comment] 2019-10-16 01:24
@kirchet  fitcontent should override everything and literally fit it 100% it in all ways. yes.

**Comment by Rishabhai** [comment] 2019-11-14 05:51
i am also facing an issue while using chart.timeScale().fitContent()  few data points are plotted out of visiable range and i have to scroll to see those. Check my implementation here https://jsfiddle.net/emdqwfxt/22/

**Comment by kirchet** [comment] 2019-11-14 11:52
@Rishabhai, this is almost the same. This is caused by the minimum bar spacing restriction

**Comment by timocov** [comment] 2019-11-15 12:46
See also my remark here https://github.com/tradingview/lightweight-charts/issues/251#issuecomment-552865393.

**Comment by timocov** [comment] 2019-11-15 12:49
Actually it's pretty the same as #251 - it's not so easy to draw data correctly if there are several bars per 1px. We can easily increase limitation of max bar spacing, but not so easy for limitation of min bar spacing.

**Comment by krtschmr** [comment] 2019-11-15 12:52
well, litterally every other chart library can draw a graph with 2 or 3 points.. crazy that tradingview cant

**Comment by timocov** [comment] 2019-11-15 13:18
> tradingview cant

@krtschmr Heh, we can, but we trying to think about UX and how it will look like. Just imaging - you need to draw values 100, 120, 140 at the same pixel, how it should be look? Vertical line from 100 to 140? Or only point at 140? Or something else? It might mislead.

**Comment by timocov** [comment] 2020-02-21 08:41
Hi @krtschmr, is it possible to get your dataset from charts in https://github.com/tradingview/lightweight-charts/issues/229#issuecomment-540505343?

**Comment by timocov** [comment] 2020-03-06 08:17
Hey @krtschmr, could you please check this out with 2.0.0 version of the library? We made some changes there, and I think it'd be better for your case.

**Comment by krtschmr** [comment] 2020-03-15 17:09
Hi @timocov  i'm not on the project anymore. sorry, can't help

**Comment by timocov** [comment] 2020-03-17 08:34
Okay, no problem. If somebody faced this issue - feel free to ping me and describe your case and I'll re-open it. So for now I'm going to close the issue.

**Closed by timocov** 2020-03-17 08:34 UTC
Labels: bug

**Comment by HirulkarRajesh** [comment] 2020-04-08 10:09
@timocov it very important for all users of charts
I have one requirement i need to set time scale start from 00:00 am time to 23:59 pm event don't have datavalue for that time is it possible, now what happened we have data for some hr like 1 or 2 hr data we have but i want to show time scale of 24 hr window
meanse time scle should be like below
|00:00-----------------------------------------------------------------------23:59|

Please reploy some its urgent and IMP i hop u understand

**Comment by tankorsmash** [comment] 2020-10-19 02:57
https://jsfiddle.net/xLb0jomc/1/ here's a current example where I can only see a section of my data, whereas I'd like to be able to see all of it:

![image](https://user-images.githubusercontent.com/1312390/96396431-3613d200-1195-11eb-9473-3737264764a2.png)

then to the left quite a bit:

![image](https://user-images.githubusercontent.com/1312390/96396461-44fa8480-1195-11eb-9512-6956051e093f.png)

I've been trying to come up with ways to work around it (maybe averaging data points together), but I can't come up with anything that'd preserve data.

**Comment by NateAGeek** [comment] 2021-12-09 08:08
I have also used the fitContent method for my line data. There seems to be still some margin on the right and left and bottom. Is that related to this issue @timocov? Let me know if there is any help I can provide too, as I do have some cycles to spare in addressing this issue.

![image](https://user-images.githubusercontent.com/1813055/145357971-53a2f4ad-1b13-4fce-bfe5-c500b7c4f6fe.png)

**Comment by timocov** [comment] 2021-12-09 09:23
@NateAGeek `fitContent` doesn't know the possible width of a bar thus according to https://tradingview.github.io/lightweight-charts/docs/time-scale#logical-range it fits for the whole bar. If you know exactly the type of the chart and how you want to display the chart, you could adjust the visible range by using [`setVisibleLogicalRange`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#setvisiblelogicalrange) method.

**Comment by NateAGeek** [comment] 2021-12-10 00:05
@timocov Sorry, might have been some confusion on my part. But the right and left ends are final data points. There is not any other data after or before, yet there is still some padding around the chart it appears. I'll fork and see if I can understand what the issue might be. I did use setVisibleLogicalRange and also tried to change the barSpacing.

**Comment by NateAGeek** [comment] 2021-12-10 04:42
Ah, after reviewing the documentation I was able to get the line and start and end to stretch the whole content. I think I was confused with the concept of a line point vs bar. For reference anyone looking at this issue. LineSeries data points are technically drawn in the middle of the bar. So, if you want to fully stretch the LineSeries then you can do `chart.timeScale().setVisibleLogicalRange({from: 0.5, to: 8.5})`
for a dataset with 10 data entries.

Thank you @timocov for answering my questions and putting in great support for this project. I can see you do a good/great amount of helping 😄

**Comment by timocov** [comment] 2021-12-10 10:40
> LineSeries data points are technically drawn in the middle of the bar. So, if you want to fully stretch the LineSeries then you can do

Yes, exactly! That's what I meant in `doesn't know the possible width`, because for candlestick it is almost the whole bar, for line it is nothing, for other type of charts it is different.

**Comment by ravenflores** [comment] 2023-01-15 05:26
> chart.timeScale().setVisibleLogicalRange({from: 0.5, to: 8.5})

thanks mate finally able to fix it

**Comment by maryleshko** [comment] 2023-01-30 06:52
@timocov Hi! I have almost the same problem, but I can not fix it. When I have less than 10 data points (I think 10 but it may be more a bit), chart doesn't fit all the available space. 
I tried `chart.timeScale().fitContent()`, `timeScale().setVisibleLogicalRange(range: FromToRange(from: 139.8, to: 143.05))` and a lot of other things, but nothing is working. Could you please assist me we this issue?

<img width="345" alt="Screenshot 2023-01-30 at 07 50 21" src="https://user-images.githubusercontent.com/71191448/215407407-6eebc8dc-3079-45bb-8e00-023febb3c0ba.png">

**Comment by alx-developer** [comment] 2023-11-21 02:13
> @timocov Hi! I have almost the same problem, but I can not fix it. When I have less than 10 data points (I think 10 but it may be more a bit), chart doesn't fit all the available space. I tried `chart.timeScale().fitContent()`, `timeScale().setVisibleLogicalRange(range: FromToRange(from: 139.8, to: 143.05))` and a lot of other things, but nothing is working. Could you please assist me we this issue? For example, these screenshots for 3 and 2 values <img alt="Screenshot 2023-01-30 at 07 50 21" width="345" src="https://user-images.githubusercontent.com/71191448/215407407-6eebc8dc-3079-45bb-8e00-023febb3c0ba.png">
> 
> <img alt="Screenshot 2023-01-30 at 07 55 06" width="338" src="https://user-images.githubusercontent.com/71191448/215408138-7ce34969-d127-4257-816f-afe144be6ebd.png">

Hi @maryleshko, did you fix it? I have the same problem

**Comment by maryleshko** [comment] 2023-12-01 09:05
Hi @alx-developer ! Unfortunately, I haven't fixed it, I just decided to add a kind of default values at the beginning. Probably it can work also for you.

**Comment by zed-wong** [comment] 2023-12-26 02:25
Can I use fitContent via options? I'm currently using `https://github.com/trash-and-fire/svelte-lightweight-charts` and seems like there's not a way to call the fitContent()

**Comment by xuzhaobin** [comment] 2024-05-24 03:12
Hi @maryleshko Any updates?
